/**
 * Copyright (c) 2023-2026 by Takahiko Tominaga
 * This software is licensed under the MIT License (MIT).
 * For more information see LICENSE or https://opensource.org/licenses/MIT
 */

package ldbc.mysql

import java.time.format.DateTimeFormatter
import java.time.temporal.TemporalAccessor

import ldbc.sql.ResultSet

import ldbc.fx.{ Fx, Ref }
import ldbc.mysql.data.{ ColumnValueDecoder, TextColumnValueDecoder }
import ldbc.mysql.net.packet.response.*
import ldbc.mysql.net.Protocol
import ldbc.mysql.util.Version

/**
 * A table of data representing a database result set, which is usually generated by executing a statement that queries the database.
 */
private[ldbc] case class ResultSetImpl(
  protocol:             Protocol,
  columns:              Vector[ColumnDefinitionPacket],
  records:              Vector[ResultSetRowPacket],
  serverVariables:      Map[String, String],
  version:              Version,
  isClosed:             Ref[Boolean],
  fetchSize:            Ref[Int],
  useCursorFetch:       Boolean,
  useServerPrepStmts:   Boolean,
  decoder:              ColumnValueDecoder,
  resultSetType:        Int            = ResultSet.TYPE_FORWARD_ONLY,
  resultSetConcurrency: Int            = ResultSet.CONCUR_READ_ONLY,
  statement:            Option[String] = None
) extends SharedResultSet:

  override def next(): Fx[Boolean] =
    checkClosed().map { _ =>
      if currentCursor < records.length then
        // Use apply instead of lift for index access from a performance standpoint.
        currentRow    = Some(records(currentCursor))
        currentCursor = currentCursor + 1
        true
      else
        currentCursor = currentCursor + 1
        currentRow    = None
        false
    }

private[ldbc] object ResultSetImpl:

  private[ldbc] final val CLOSED_MESSAGE = "Operation not allowed after ResultSet closed"

  private[ldbc] def temporalDecode[A <: TemporalAccessor](
    formatter: DateTimeFormatter,
    parse:     (String, DateTimeFormatter) => A
  ): String => A = str => parse(str, formatter)

  def apply(
    protocol:           Protocol,
    columns:            Vector[ColumnDefinitionPacket],
    records:            Vector[ResultSetRowPacket],
    serverVariables:    Map[String, String],
    version:            Version,
    isClosed:           Ref[Boolean],
    fetchSize:          Ref[Int],
    useCursorFetch:     Boolean,
    useServerPrepStmts: Boolean,
    decoder:            ColumnValueDecoder
  ): ResultSetImpl =
    ResultSetImpl(
      protocol,
      columns,
      records,
      serverVariables,
      version,
      isClosed,
      fetchSize,
      useCursorFetch,
      useServerPrepStmts,
      decoder,
      ResultSet.TYPE_FORWARD_ONLY
    )

  def empty(
    protocol:           Protocol,
    serverVariables:    Map[String, String],
    version:            Version,
    isClosed:           Ref[Boolean],
    fetchSize:          Ref[Int],
    useCursorFetch:     Boolean,
    useServerPrepStmts: Boolean,
    decoder:            ColumnValueDecoder = TextColumnValueDecoder
  ): ResultSetImpl =
    this.apply(
      protocol,
      Vector.empty,
      Vector.empty,
      serverVariables,
      version,
      isClosed,
      fetchSize,
      useCursorFetch,
      useServerPrepStmts,
      decoder
    )
