coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        informational: true
  ignore:
    - "benchmark"
    - "examples"
    - "plugin"
    - "docs"
    - "core"
    - "module/ldbc-sql"
    - "module/jdbc-connector"
    - "module/ldbc-schemaspy"
    - "tests/shared/src/main/scala/ldbc/tests/model"
    - "module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/CallableStatementImpl.scala"
    - "module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/ServerPreparedStatement.scala"
    - "module/ldbc-connector/jvm/src/main/scala/ldbc/connector/SSLPlatform.scala"
    - "module/ldbc-connector/shared/src/main/scala/ldbc/connector/net/protocol/Initial.scala"
    - "module/ldbc-schema/src/main/scala/ldbc/schema/Character.scala"
    - "module/ldbc-hikari/src/main/scala/ldbc/hikari/Configuration.scala"
    - "module/ldbc-dsl/src/main/scala/ldbc/dsl/ResultSetConsumer.scala"
