coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        informational: true
  ignore:
    - "benchmark"
    - "examples"
    - "plugin"
    - "docs"
    - "core"
    - "modules/sql"
    - "modules/core"
    - "modules/jdbc-connector"
    - "tests/shared/src/main/scala/ldbc/tests/model"
    - "modules/connector/shared/src/main/scala/ldbc/connector/net/protocol/CallableStatementImpl.scala"
    - "modules/connector/shared/src/main/scala/ldbc/connector/net/protocol/ServerPreparedStatement.scala"
    - "modules/connector/jvm/src/main/scala/ldbc/connector/SSLPlatform.scala"
    - "modules/connector/shared/src/main/scala/ldbc/connector/net/protocol/Initial.scala"
    - "modules/schema/src/main/scala/ldbc/schema/Character.scala"
    - "modules/dsl/src/main/scala/ldbc/dsl/ResultSetConsumer.scala"
    - "modules/zio-interop/src/main/scala/ldbc/zio/interop/package.scala"
