/**
 * Copyright (c) 2023-2026 by Takahiko Tominaga
 * This software is licensed under the MIT License (MIT).
 * For more information see LICENSE or https://opensource.org/licenses/MIT
 */

package ldbc.mysql.net.protocol

import ldbc.sql.SQLException
import java.time.*

import scala.collection.immutable.{ ListMap, SortedMap }

import ldbc.fx.{ Fx, Ref }
import ldbc.fx.syntax.*

import ldbc.mysql.telemetry.{ DbAttributes, ErrorAttributes }
import ldbc.mysql.telemetry.{ Span, StatusCode, Tracer }
import ldbc.sql.Attribute

import ldbc.sql.{ CallableStatement, DatabaseMetaData, ParameterMetaData, ResultSet, Statement }

import ldbc.mysql.*
import ldbc.mysql.data.*
import ldbc.mysql.net.packet.request.*
import ldbc.mysql.net.packet.response.*
import ldbc.mysql.net.Protocol
import ldbc.mysql.syntax.*
import ldbc.mysql.telemetry.*

case class CallableStatementImpl(
  protocol:                Protocol,
  serverVariables:         Map[String, String],
  sql:                     String,
  paramInfo:               CallableStatementImpl.ParamInfo,
  params:                  Ref[SortedMap[Int, Parameter]],
  batchedArgs:             Ref[Vector[String]],
  connectionClosed:        Ref[Boolean],
  statementClosed:         Ref[Boolean],
  resultSetClosed:         Ref[Boolean],
  currentResultSet:        Ref[Option[ResultSet[Fx]]],
  outputParameterResult:   Ref[Option[ResultSetImpl]],
  resultSets:              Ref[List[ResultSetImpl]],
  parameterIndexToRsIndex: Ref[Map[Int, Int]],
  updateCount:             Ref[Long],
  moreResults:             Ref[Boolean],
  autoGeneratedKeys:       Ref[Int],
  lastInsertId:            Ref[Long],
  fetchSize:               Ref[Int],
  useCursorFetch:          Boolean,
  useServerPrepStmts:      Boolean,
  resultSetType:           Int             = ResultSet.TYPE_FORWARD_ONLY,
  resultSetConcurrency:    Int             = ResultSet.CONCUR_READ_ONLY,
  telemetryConfig:         TelemetryConfig = TelemetryConfig.default,
  databaseMetrics:         DatabaseMetrics
)(using Tracer, Exchange)
  extends CallableStatement[Fx],
          SharedPreparedStatement:

  private val baseAttributes    = buildBaseAttributes(protocol)
  private val metricsAttributes = buildMetricsAttributes(protocol)

  override def executeQuery(): Fx[ResultSet[Fx]] =
    checkClosed() *>
      checkNullOrEmptyQuery(sql) *>
      exchange[ResultSet[Fx]](
        telemetryConfig.resolveSpanName(
          sql,
          TelemetrySpanName.STMT_CALLABLE,
          protocol.hostInfo.database,
          Some(protocol.hostInfo.host),
          Some(protocol.hostInfo.port)
        )
      ) { (span: Span) =>
        val processedSql    = telemetryConfig.processQueryText(sql)
        val queryAttributes = baseAttributes ++ List(
          DbAttributes.DbQueryText(processedSql)
        )

        for
          _         <- span.addAttributes(queryAttributes*)
          resultSet <- withDurationMetrics(
                         if sql.toUpperCase.startsWith("CALL") then
                           executeCallStatement(span).flatMap { resultSets =>
                             resultSets.headOption match
                               case None =>
                                 for
                                   resultSet <- Fx.pure(
                                                  ResultSetImpl.empty(
                                                    protocol,
                                                    serverVariables,
                                                    protocol.initialPacket.serverVersion,
                                                    resultSetClosed,
                                                    fetchSize,
                                                    useCursorFetch,
                                                    useServerPrepStmts
                                                  )
                                                )
                                   _ <- currentResultSet.set(Some(resultSet))
                                 yield resultSet
                               case Some(resultSet) =>
                                 currentResultSet.update(_ => Some(resultSet)) *> Fx.pure(resultSet)
                           } <* retrieveOutParams()
                         else
                           params.get.flatMap { params =>
                             protocol.resetSequenceId *>
                               protocol.send(
                                 ComQueryPacket(
                                   buildQuery(sql, params),
                                   protocol.initialPacket.capabilityFlags,
                                   ListMap.empty
                                 )
                               ) *>
                               receiveQueryResult()
                           }
                         ,
                         metricsAttributes*
                       )
          _ <- resultSet match
                 case rs: ResultSetImpl =>
                   databaseMetrics.recordReturnedRows(rs.records.size.toLong, metricsAttributes*)
                 case _ => Fx.unit
        yield resultSet
      } <* params.set(SortedMap.empty)

  override def executeLargeUpdate(): Fx[Long] =
    checkClosed() *>
      checkNullOrEmptyQuery(sql) *>
      exchange[Long](
        telemetryConfig.resolveSpanName(
          sql,
          TelemetrySpanName.STMT_CALLABLE,
          protocol.hostInfo.database,
          Some(protocol.hostInfo.host),
          Some(protocol.hostInfo.port)
        )
      ) { (span: Span) =>
        val processedSql    = telemetryConfig.processQueryText(sql)
        val queryAttributes = baseAttributes ++ List(
          DbAttributes.DbQueryText(processedSql)
        )

        span.addAttributes(queryAttributes*) *>
          withDurationMetrics(
            if sql.toUpperCase.startsWith("CALL") then
              executeCallStatement(span).flatMap { resultSets =>
                resultSets.headOption match
                  case None =>
                    for
                      resultSet <- Fx.pure(
                                     ResultSetImpl.empty(
                                       protocol,
                                       serverVariables,
                                       protocol.initialPacket.serverVersion,
                                       resultSetClosed,
                                       fetchSize,
                                       useCursorFetch,
                                       useServerPrepStmts
                                     )
                                   )
                      _ <- currentResultSet.set(Some(resultSet))
                    yield resultSet
                  case Some(resultSet) =>
                    currentResultSet.update(_ => Some(resultSet)) *> Fx.pure(resultSet)
              } *> retrieveOutParams() *> Fx.pure(-1L)
            else
              params.get.flatMap { params =>
                sendQuery(buildQuery(sql, params)).flatMap {
                  case result: OKPacket => lastInsertId.set(result.lastInsertId) *> Fx.pure(result.affectedRows)
                  case error: ERRPacket =>
                    val exception = error.toException(Some(sql), None)
                    span.addAttributes(error.attributes*) *>
                      span.recordException(exception, error.attributes*) *>
                      span.setStatus(StatusCode.Error, exception.getMessage) *>
                      Fx.raiseError(exception)
                  case eof: EOFPacket =>
                    val exception = new SQLException("Unexpected EOF packet")
                    span.addAttribute(ErrorAttributes.ErrorType(exception.getClass.getName)) *>
                      span.recordException(exception, eof.attribute) *>
                      span.setStatus(StatusCode.Error, exception.getMessage) *>
                      Fx.raiseError(exception)
                }
              }
            ,
            metricsAttributes*
          )
      }

  override def execute(): Fx[Boolean] =
    checkClosed() *>
      checkNullOrEmptyQuery(sql) *>
      exchange[Boolean](
        telemetryConfig.resolveSpanName(
          sql,
          TelemetrySpanName.STMT_CALLABLE,
          protocol.hostInfo.database,
          Some(protocol.hostInfo.host),
          Some(protocol.hostInfo.port)
        )
      ) { (span: Span) =>
        if sql.toUpperCase.startsWith("CALL") then
          executeCallStatement(span).flatMap { results =>
            moreResults.update(_ => results.nonEmpty) *>
              currentResultSet.update(_ => results.headOption) *>
              resultSets.set(results.toList) *>
              Fx.pure(results.nonEmpty)
          } <* retrieveOutParams()
        else
          params.get
            .flatMap { params =>
              val processedSql    = telemetryConfig.processQueryText(sql)
              val queryAttributes = baseAttributes ++ List(
                DbAttributes.DbQueryText(processedSql)
              )

              span.addAttributes(queryAttributes*) *>
                sendQuery(buildQuery(sql, params)).flatMap {
                  case result: OKPacket => lastInsertId.set(result.lastInsertId) *> Fx.pure(result.affectedRows)
                  case error: ERRPacket =>
                    val exception = error.toException(Some(sql), None)
                    span.addAttributes(error.attributes*) *>
                      span.recordException(exception, error.attributes*) *>
                      span.setStatus(StatusCode.Error, exception.getMessage) *>
                      Fx.raiseError(exception)
                  case eof: EOFPacket =>
                    val exception = new SQLException("Unexpected EOF packet")
                    span.addAttribute(ErrorAttributes.ErrorType(exception.getClass.getName)) *>
                      span.recordException(exception, eof.attribute) *>
                      span.setStatus(StatusCode.Error, exception.getMessage) *>
                      Fx.raiseError(exception)
                }
            }
            .map(_ => false)
      }

  override def getMoreResults(): Fx[Boolean] =
    checkClosed() *> moreResults.get.flatMap { isMoreResults =>
      if isMoreResults then
        resultSets.get.flatMap {
          case Nil               => moreResults.set(false) *> Fx.pure(false)
          case resultSet :: tail =>
            currentResultSet.set(Some(resultSet)) *> resultSets.set(tail) *> Fx.pure(true)
        }
      else Fx.pure(false)
    }

  override def addBatch(): Fx[Unit] =
    checkClosed() *>
      checkNullOrEmptyQuery(sql) *> (
        sql.toUpperCase match
          case q if q.startsWith("CALL") =>
            setInOutParamsOnServer(paramInfo) *> setOutParams()
          case _ => Fx.unit
      ) *>
      params.get.flatMap { params =>
        batchedArgs.update(_ :+ buildBatchQuery(sql, params))
      } *>
      params.set(SortedMap.empty)

  override def clearBatch(): Fx[Unit] = batchedArgs.set(Vector.empty)

  override def executeLargeBatch(): Fx[Array[Long]] =
    checkClosed() *>
      checkNullOrEmptyQuery(sql) *>
      exchange[Array[Long]](TelemetrySpanName.STMT_CALLABLE) { (span: Span) =>
        batchedArgs.get.flatMap { args =>
          val batchAttributes = baseAttributes ++
            List(DbAttributes.DbOperationName(TelemetryAttribute.SqlOperation.BATCH)) ++
            TelemetryAttribute.dbOperationBatchSize(args.length).toList

          if args.isEmpty then Fx.pure(Array.empty)
          else
            sql.toUpperCase match
              case q if q.startsWith("INSERT") =>
                withDurationMetrics(
                  span.addAttributes(batchAttributes*) *>
                    sendQuery(sql.split("VALUES").head + " VALUES" + args.mkString(","))
                      .flatMap {
                        case _: OKPacket      => Fx.pure(Array.fill(args.length)(Statement.SUCCESS_NO_INFO.toLong))
                        case error: ERRPacket =>
                          val exception = error.toException(Some(sql), None)
                          span.addAttributes(error.attributes*) *>
                            span.recordException(exception, error.attributes*) *>
                            span.setStatus(StatusCode.Error, exception.getMessage) *>
                            Fx.raiseError(exception)
                        case eof: EOFPacket =>
                          val exception = new SQLException("Unexpected EOF packet")
                          span.addAttribute(ErrorAttributes.ErrorType(exception.getClass.getName)) *>
                            span.recordException(exception, eof.attribute) *>
                            span.setStatus(StatusCode.Error, exception.getMessage) *>
                            Fx.raiseError(exception)
                      },
                  metricsAttributes*
                )
              case q if q.startsWith("UPDATE") || q.startsWith("DELETE") || q.startsWith("CALL") =>
                withDurationMetrics(
                  span.addAttributes(batchAttributes*) *>
                    protocol.resetSequenceId *>
                    protocol.comSetOption(EnumMySQLSetOption.MYSQL_OPTION_MULTI_STATEMENTS_ON) *>
                    protocol.resetSequenceId *>
                    protocol.send(
                      ComQueryPacket(
                        args.mkString(";"),
                        protocol.initialPacket.capabilityFlags,
                        ListMap.empty
                      )
                    ) *>
                    args
                      .foldLeft(Fx.pure(Vector.empty[Long])) { ($acc, _) =>
                        for
                          acc    <- $acc
                          result <-
                            protocol
                              .receive(GenericResponsePackets.decoder(protocol.initialPacket.capabilityFlags))
                              .flatMap {
                                case result: OKPacket =>
                                  lastInsertId.set(result.lastInsertId) *> Fx.pure(acc :+ result.affectedRows)
                                case error: ERRPacket =>
                                  val exception = error.toException("Failed to execute batch", acc)
                                  span.addAttributes(error.attributes*) *>
                                    span.recordException(exception, error.attributes*) *>
                                    span.setStatus(StatusCode.Error, exception.getMessage) *>
                                    Fx.raiseError(exception)
                                case eof: EOFPacket =>
                                  val exception = new SQLException("Unexpected EOF packet")
                                  span.addAttribute(ErrorAttributes.ErrorType(exception.getClass.getName)) *>
                                    span.recordException(exception, eof.attribute) *>
                                    span.setStatus(StatusCode.Error, exception.getMessage) *>
                                    Fx.raiseError(exception)
                              }
                        yield result
                      }
                      .map(_.toArray) <*
                    protocol.resetSequenceId <*
                    protocol.comSetOption(EnumMySQLSetOption.MYSQL_OPTION_MULTI_STATEMENTS_OFF),
                  metricsAttributes*
                )
              case _ =>
                Fx.raiseError(
                  new SQLException("The batch query must be an INSERT, UPDATE, or DELETE, CALL statement.")
                )
        }
      } <* params.set(SortedMap.empty) <* batchedArgs.set(Vector.empty)

  override def close(): Fx[Unit] = statementClosed.set(true) *> resultSetClosed.set(true)

  override def registerOutParameter(parameterIndex: Int, sqlType: Int): Fx[Unit] =
    if paramInfo.numParameters > 0 then
      paramInfo.parameterList.find(_.index == parameterIndex) match
        case Some(param) =>
          (if param.jdbcType == sqlType then Fx.unit
           else
             Fx.raiseError(
               new SQLException(
                 "The type specified for the parameter does not match the type registered as a procedure."
               )
             )
          ) *> (
            if param.isOut && param.isIn then
              val paramName          = param.paramName.getOrElse("nullnp" + param.index)
              val inOutParameterName = mangleParameterName(paramName)

              val queryBuf = new StringBuilder(4 + inOutParameterName.length + 1)
              queryBuf.append("SET ")
              queryBuf.append(inOutParameterName)
              queryBuf.append("=")

              params.get.flatMap { params =>
                val sql = queryBuf.toString ++ params.get(param.index).fold("NULL")(_.sql)
                sendQuery(sql).flatMap {
                  case _: OKPacket      => Fx.unit
                  case error: ERRPacket => Fx.raiseError(error.toException(Some(sql), None))
                  case _: EOFPacket     => Fx.raiseError(new SQLException("Unexpected EOF packet"))
                }
              }
            else Fx.raiseError(new SQLException("No output parameters returned by procedure."))
          )
        case None =>
          Fx.raiseError(
            new SQLException(s"Parameter index of $parameterIndex is out of range (1, ${ paramInfo.numParameters })")
          )
    else Fx.unit

  override def getString(parameterIndex: Int): Fx[Option[String]] =
    for
      resultSet <- checkBounds(parameterIndex) *> getOutputParameters()
      paramMap  <- parameterIndexToRsIndex.get
      index = paramMap.getOrElse(parameterIndex, parameterIndex)
      value <-
        (if index == CallableStatementImpl.NOT_OUTPUT_PARAMETER_INDICATOR then
           Fx.raiseError(new SQLException(s"Parameter $parameterIndex is not registered as an output parameter"))
         else resultSet.getString(index))
    yield Option(value)

  override def getBoolean(parameterIndex: Int): Fx[Boolean] =
    for
      resultSet <- checkBounds(parameterIndex) *> getOutputParameters()
      paramMap  <- parameterIndexToRsIndex.get
      index = paramMap.getOrElse(parameterIndex, parameterIndex)
      value <-
        (if index == CallableStatementImpl.NOT_OUTPUT_PARAMETER_INDICATOR then
           Fx.raiseError(new SQLException(s"Parameter $parameterIndex is not registered as an output parameter"))
         else resultSet.getBoolean(index))
    yield value

  override def getByte(parameterIndex: Int): Fx[Byte] =
    for
      resultSet <- checkBounds(parameterIndex) *> getOutputParameters()
      paramMap  <- parameterIndexToRsIndex.get
      index = paramMap.getOrElse(parameterIndex, parameterIndex)
      value <-
        (if index == CallableStatementImpl.NOT_OUTPUT_PARAMETER_INDICATOR then
           Fx.raiseError(new SQLException(s"Parameter $parameterIndex is not registered as an output parameter"))
         else resultSet.getByte(index))
    yield value

  override def getShort(parameterIndex: Int): Fx[Short] =
    for
      resultSet <- checkBounds(parameterIndex) *> getOutputParameters()
      paramMap  <- parameterIndexToRsIndex.get
      index = paramMap.getOrElse(parameterIndex, parameterIndex)
      value <-
        (if index == CallableStatementImpl.NOT_OUTPUT_PARAMETER_INDICATOR then
           Fx.raiseError(new SQLException(s"Parameter $parameterIndex is not registered as an output parameter"))
         else resultSet.getShort(index))
    yield value

  override def getInt(parameterIndex: Int): Fx[Int] =
    for
      resultSet <- checkBounds(parameterIndex) *> getOutputParameters()
      paramMap  <- parameterIndexToRsIndex.get
      index = paramMap.getOrElse(parameterIndex, parameterIndex)
      value <-
        (if index == CallableStatementImpl.NOT_OUTPUT_PARAMETER_INDICATOR then
           Fx.raiseError(new SQLException(s"Parameter $parameterIndex is not registered as an output parameter"))
         else resultSet.getInt(index))
    yield value

  override def getLong(parameterIndex: Int): Fx[Long] =
    for
      resultSet <- checkBounds(parameterIndex) *> getOutputParameters()
      paramMap  <- parameterIndexToRsIndex.get
      index = paramMap.getOrElse(parameterIndex, parameterIndex)
      value <-
        (if index == CallableStatementImpl.NOT_OUTPUT_PARAMETER_INDICATOR then
           Fx.raiseError(new SQLException(s"Parameter $parameterIndex is not registered as an output parameter"))
         else resultSet.getLong(index))
    yield value

  override def getFloat(parameterIndex: Int): Fx[Float] =
    for
      resultSet <- checkBounds(parameterIndex) *> getOutputParameters()
      paramMap  <- parameterIndexToRsIndex.get
      index = paramMap.getOrElse(parameterIndex, parameterIndex)
      value <-
        (if index == CallableStatementImpl.NOT_OUTPUT_PARAMETER_INDICATOR then
           Fx.raiseError(new SQLException(s"Parameter $parameterIndex is not registered as an output parameter"))
         else resultSet.getFloat(index))
    yield value

  override def getDouble(parameterIndex: Int): Fx[Double] =
    for
      resultSet <- checkBounds(parameterIndex) *> getOutputParameters()
      paramMap  <- parameterIndexToRsIndex.get
      index = paramMap.getOrElse(parameterIndex, parameterIndex)
      value <-
        (if index == CallableStatementImpl.NOT_OUTPUT_PARAMETER_INDICATOR then
           Fx.raiseError(new SQLException(s"Parameter $parameterIndex is not registered as an output parameter"))
         else resultSet.getDouble(index))
    yield value

  override def getBytes(parameterIndex: Int): Fx[Option[Array[Byte]]] =
    for
      resultSet <- checkBounds(parameterIndex) *> getOutputParameters()
      paramMap  <- parameterIndexToRsIndex.get
      index = paramMap.getOrElse(parameterIndex, parameterIndex)
      value <-
        (if index == CallableStatementImpl.NOT_OUTPUT_PARAMETER_INDICATOR then
           Fx.raiseError(new SQLException(s"Parameter $parameterIndex is not registered as an output parameter"))
         else resultSet.getBytes(index))
    yield Option(value)

  override def getDate(parameterIndex: Int): Fx[Option[LocalDate]] =
    for
      resultSet <- checkBounds(parameterIndex) *> getOutputParameters()
      paramMap  <- parameterIndexToRsIndex.get
      index = paramMap.getOrElse(parameterIndex, parameterIndex)
      value <-
        (if index == CallableStatementImpl.NOT_OUTPUT_PARAMETER_INDICATOR then
           Fx.raiseError(new SQLException(s"Parameter $parameterIndex is not registered as an output parameter"))
         else resultSet.getDate(index))
    yield Option(value)

  override def getTime(parameterIndex: Int): Fx[Option[LocalTime]] =
    for
      resultSet <- checkBounds(parameterIndex) *> getOutputParameters()
      paramMap  <- parameterIndexToRsIndex.get
      index = paramMap.getOrElse(parameterIndex, parameterIndex)
      value <-
        (if index == CallableStatementImpl.NOT_OUTPUT_PARAMETER_INDICATOR then
           Fx.raiseError(new SQLException(s"Parameter $parameterIndex is not registered as an output parameter"))
         else resultSet.getTime(index))
    yield Option(value)

  override def getTimestamp(parameterIndex: Int): Fx[Option[LocalDateTime]] =
    for
      resultSet <- checkBounds(parameterIndex) *> getOutputParameters()
      paramMap  <- parameterIndexToRsIndex.get
      index = paramMap.getOrElse(parameterIndex, parameterIndex)
      value <-
        (if index == CallableStatementImpl.NOT_OUTPUT_PARAMETER_INDICATOR then
           Fx.raiseError(new SQLException(s"Parameter $parameterIndex is not registered as an output parameter"))
         else resultSet.getTimestamp(index))
    yield Option(value)

  override def getBigDecimal(parameterIndex: Int): Fx[Option[BigDecimal]] =
    for
      resultSet <- checkBounds(parameterIndex) *> getOutputParameters()
      paramMap  <- parameterIndexToRsIndex.get
      index = paramMap.getOrElse(parameterIndex, parameterIndex)
      value <-
        (if index == CallableStatementImpl.NOT_OUTPUT_PARAMETER_INDICATOR then
           Fx.raiseError(new SQLException(s"Parameter $parameterIndex is not registered as an output parameter"))
         else resultSet.getBigDecimal(index))
    yield Option(value)

  override def getString(parameterName: String): Fx[Option[String]] =
    for
      resultSet <- getOutputParameters()
      value     <- resultSet.getString(mangleParameterName(parameterName))
    yield Option(value)

  override def getBoolean(parameterName: String): Fx[Boolean] =
    for
      resultSet <- getOutputParameters()
      value     <- resultSet.getBoolean(mangleParameterName(parameterName))
    yield value

  override def getByte(parameterName: String): Fx[Byte] =
    for
      resultSet <- getOutputParameters()
      value     <- resultSet.getByte(mangleParameterName(parameterName))
    yield value

  override def getShort(parameterName: String): Fx[Short] =
    for
      resultSet <- getOutputParameters()
      value     <- resultSet.getShort(mangleParameterName(parameterName))
    yield value

  override def getInt(parameterName: String): Fx[Int] =
    for
      resultSet <- getOutputParameters()
      value     <- resultSet.getInt(mangleParameterName(parameterName))
    yield value

  override def getLong(parameterName: String): Fx[Long] =
    for
      resultSet <- getOutputParameters()
      value     <- resultSet.getLong(mangleParameterName(parameterName))
    yield value

  override def getFloat(parameterName: String): Fx[Float] =
    for
      resultSet <- getOutputParameters()
      value     <- resultSet.getFloat(mangleParameterName(parameterName))
    yield value

  override def getDouble(parameterName: String): Fx[Double] =
    for
      resultSet <- getOutputParameters()
      value     <- resultSet.getDouble(mangleParameterName(parameterName))
    yield value

  override def getBytes(parameterName: String): Fx[Option[Array[Byte]]] =
    for
      resultSet <- getOutputParameters()
      value     <- resultSet.getBytes(mangleParameterName(parameterName))
    yield Option(value)

  override def getDate(parameterName: String): Fx[Option[LocalDate]] =
    for
      resultSet <- getOutputParameters()
      value     <- resultSet.getDate(mangleParameterName(parameterName))
    yield Option(value)

  override def getTime(parameterName: String): Fx[Option[LocalTime]] =
    for
      resultSet <- getOutputParameters()
      value     <- resultSet.getTime(mangleParameterName(parameterName))
    yield Option(value)

  override def getTimestamp(parameterName: String): Fx[Option[LocalDateTime]] =
    for
      resultSet <- getOutputParameters()
      value     <- resultSet.getTimestamp(mangleParameterName(parameterName))
    yield Option(value)

  override def getBigDecimal(parameterName: String): Fx[Option[BigDecimal]] =
    for
      resultSet <- getOutputParameters()
      value     <- resultSet.getBigDecimal(mangleParameterName(parameterName))
    yield Option(value)

  private def setParameter(index: Int, value: String): Fx[Unit] =
    params.update(_ + (index -> Parameter.parameter(value)))

  private def sendQuery(sql: String): Fx[GenericResponsePackets] =
    checkNullOrEmptyQuery(sql) *> protocol.resetSequenceId *> protocol.send(
      ComQueryPacket(sql, protocol.initialPacket.capabilityFlags, ListMap.empty)
    ) *> protocol.receive(GenericResponsePackets.decoder(protocol.initialPacket.capabilityFlags))

  private def receiveUntilOkPacket(resultSets: Vector[ResultSetImpl]): Fx[Vector[ResultSetImpl]] =
    protocol.receive(ColumnsNumberPacket.decoder(protocol.initialPacket.capabilityFlags)).flatMap {
      case _: OKPacket                 => Fx.pure(resultSets)
      case error: ERRPacket            => Fx.raiseError(error.toException(Some(sql), None))
      case result: ColumnsNumberPacket =>
        for
          columnDefinitions <-
            protocol.repeatProcess(
              result.size,
              ColumnDefinitionPacket.decoder(protocol.initialPacket.capabilityFlags)
            )
          resultSetRow <-
            protocol.readUntilEOF[ResultSetRowPacket](
              textResultSetRowDecoder(protocol.initialPacket.capabilityFlags)
            )
          resultSet = ResultSetImpl(
                        protocol,
                        columnDefinitions,
                        resultSetRow,
                        serverVariables,
                        protocol.initialPacket.serverVersion,
                        resultSetClosed,
                        fetchSize,
                        useCursorFetch,
                        useServerPrepStmts,
                        TextColumnValueDecoder,
                        resultSetType,
                        resultSetConcurrency
                      )
          resultSets <- receiveUntilOkPacket(resultSets :+ resultSet)
        yield resultSets
    }

  private def receiveQueryResult(): Fx[ResultSet[Fx]] =
    protocol.receive(ColumnsNumberPacket.decoder(protocol.initialPacket.capabilityFlags)).flatMap {
      case _: OKPacket =>
        Fx.pure(
          ResultSetImpl
            .empty(
              protocol,
              serverVariables,
              protocol.initialPacket.serverVersion,
              resultSetClosed,
              fetchSize,
              useCursorFetch,
              useServerPrepStmts
            )
        )
      case error: ERRPacket            => Fx.raiseError(error.toException(Some(sql), None))
      case result: ColumnsNumberPacket =>
        for
          columnDefinitions <-
            protocol.repeatProcess(
              result.size,
              ColumnDefinitionPacket.decoder(protocol.initialPacket.capabilityFlags)
            )
          resultSetRow <- protocol.readUntilEOF[ResultSetRowPacket](
                            textResultSetRowDecoder(protocol.initialPacket.capabilityFlags)
                          )
          resultSet = ResultSetImpl(
                        protocol,
                        columnDefinitions,
                        resultSetRow,
                        serverVariables,
                        protocol.initialPacket.serverVersion,
                        resultSetClosed,
                        fetchSize,
                        useCursorFetch,
                        useServerPrepStmts,
                        TextColumnValueDecoder,
                        resultSetType,
                        resultSetConcurrency
                      )
          _ <- currentResultSet.set(Some(resultSet))
        yield resultSet
    }

  /**
   * Change the parameter name to an arbitrary prefixed naming.
   *
   * @param origParameterName
   * the original parameter name
   * @return
   * the parameter name
   */
  private def mangleParameterName(origParameterName: String): String =
    val offset = if origParameterName.nonEmpty && origParameterName.charAt(0) == '@' then 1 else 0

    val paramNameBuf = new StringBuilder(
      CallableStatementImpl.PARAMETER_NAMESPACE_PREFIX.length + origParameterName.length
    )
    paramNameBuf.append(CallableStatementImpl.PARAMETER_NAMESPACE_PREFIX)
    paramNameBuf.append(origParameterName.substring(offset))

    paramNameBuf.toString

  /**
   * Set output parameters to be used by the server.
   *
   * @param paramInfo
   * the parameter information
   */
  private def setInOutParamsOnServer(paramInfo: CallableStatementImpl.ParamInfo): Fx[Unit] =
    if paramInfo.numParameters > 0 then
      paramInfo.parameterList.foldLeft(Fx.unit) { (acc, param) =>
        if param.isOut && param.isIn then
          val paramName          = param.paramName.getOrElse("nullnp" + param.index)
          val inOutParameterName = mangleParameterName(paramName)

          val queryBuf = new StringBuilder(4 + inOutParameterName.length + 1)
          queryBuf.append("SET ")
          queryBuf.append(inOutParameterName)
          queryBuf.append("=")

          acc *> params.get.flatMap { params =>
            val sql = queryBuf.toString ++ params.get(param.index).fold("NULL")(_.sql)
            sendQuery(sql).flatMap {
              case _: OKPacket      => Fx.unit
              case error: ERRPacket => Fx.raiseError(error.toException(Some(sql), None))
              case _: EOFPacket     => Fx.raiseError(new SQLException("Unexpected EOF packet"))
            }
          }
        else acc
      }
    else Fx.unit

  /**
   * Set output parameters to be handled by the client.
   */
  private def setOutParams(): Fx[Unit] =
    if paramInfo.numParameters > 0 then
      paramInfo.parameterList.foldLeft(Fx.unit) { (acc, param) =>
        if !paramInfo.isFunctionCall && param.isOut then
          val paramName        = param.paramName.getOrElse("nullnp" + param.index)
          val outParameterName = mangleParameterName(paramName)

          acc *> params.get.flatMap { params =>
            for
              outParamIndex <-
                (
                  if params.isEmpty then Fx.pure(param.index)
                  else
                    params.keys
                      .find(_ == param.index)
                      .fold(
                        Fx.raiseError(
                          new SQLException(
                            s"Parameter ${ param.index } is not registered as an output parameter"
                          )
                        )
                      )(Fx.pure(_))
                )
              _ <- setParameter(outParamIndex, outParameterName)
            yield ()
          }
        else acc
      }
    else Fx.unit

  /**
   * Issues a second query to retrieve all output parameters.
   */
  private def retrieveOutParams(): Fx[Unit] =
    val parameters = paramInfo.parameterList.foldLeft(Vector.empty[(Int, String)]) { (acc, param) =>
      if param.isOut then
        val paramName        = param.paramName.getOrElse("nullnp" + param.index)
        val outParameterName = mangleParameterName(paramName)
        acc :+ (param.index, outParameterName)
      else acc
    }

    if paramInfo.numParameters > 0 && parameters.nonEmpty then

      val sql = parameters.zipWithIndex
        .map {
          case ((_, paramName), index) =>
            val prefix = if index != 0 then ", " else ""
            val atSign = if !paramName.startsWith("@") then "@" else ""
            s"$prefix$atSign$paramName"
        }
        .mkString("SELECT ", "", "")

      checkClosed() *>
        checkNullOrEmptyQuery(sql) *>
        protocol.resetSequenceId *>
        protocol.send(ComQueryPacket(sql, protocol.initialPacket.capabilityFlags, ListMap.empty)) *>
        receiveQueryResult().flatMap {
          case resultSet: ResultSetImpl => outputParameterResult.update(_ => Some(resultSet))
        } *>
        parameters.zipWithIndex.foldLeft(Fx.unit) {
          case (acc, ((paramIndex, _), index)) =>
            acc *> parameterIndexToRsIndex.update(_ + (paramIndex -> (index + 1)))
        }
    else Fx.unit

  /**
   * Returns the ResultSet that holds the output parameters, or throws an
   * appropriate exception if none exist, or they weren't returned.
   *
   * @return
   * the ResultSet that holds the output parameters
   */
  private def getOutputParameters(): Fx[ResultSetImpl] =
    outputParameterResult.get.flatMap {
      case None =>
        if paramInfo.numParameters == 0 then Fx.raiseError(new SQLException("No output parameters registered."))
        else Fx.raiseError(new SQLException("No output parameters returned by procedure."))
      case Some(resultSet) => Fx.pure(resultSet)
    }

  /**
   * Checks if the parameter index is within the bounds of the number of parameters.
   *
   * @param paramIndex
   * the parameter index to check
   */
  private def checkBounds(paramIndex: Int): Fx[Unit] =
    if paramIndex < 1 || paramIndex > paramInfo.numParameters then
      Fx.raiseError(
        new SQLException(s"Parameter index of ${ paramIndex } is out of range (1, ${ paramInfo.numParameters })")
      )
    else Fx.unit

  /**
   * Executes a CALL/Stored function statement.
   *
   * @param span
   * the span
   * @return
   * a list of ResultSet
   */
  private def executeCallStatement(span: Span): Fx[Vector[ResultSetImpl]] =
    setInOutParamsOnServer(paramInfo) *>
      setOutParams() *>
      params.get.flatMap { params =>
        val processedSql    = telemetryConfig.processQueryText(sql)
        val queryAttributes = baseAttributes ++ List(
          DbAttributes.DbQueryText(processedSql)
        )

        span.addAttributes(queryAttributes*) *>
          protocol.resetSequenceId *>
          protocol.send(
            ComQueryPacket(buildQuery(sql, params), protocol.initialPacket.capabilityFlags, ListMap.empty)
          ) *>
          receiveUntilOkPacket(Vector.empty)
      }

object CallableStatementImpl:

  val NOT_OUTPUT_PARAMETER_INDICATOR: Int = Int.MinValue

  private val PARAMETER_NAMESPACE_PREFIX = "@ldbc_mysql_outparam_"

  /**
   * CallableStatementParameter represents a parameter in a stored procedure.
   *
   * @param paramName
   *   the name of the parameter
   * @param isIn
   *   whether the parameter is an input parameter
   * @param isOut
   *   whether the parameter is an output parameter
   * @param index
   *   the index of the parameter
   * @param jdbcType
   *   the JDBC type of the parameter
   * @param typeName
   *   the name of the type of the parameter
   * @param precision
   *   the precision of the parameter
   * @param scale
   *   the scale of the parameter
   * @param nullability
   *   the nullability of the parameter
   * @param inOutModifier
   *   the in/out modifier of the parameter
   */
  case class CallableStatementParameter(
    paramName:     Option[String],
    isIn:          Boolean,
    isOut:         Boolean,
    index:         Int,
    jdbcType:      Int,
    typeName:      Option[String],
    precision:     Int,
    scale:         Int,
    nullability:   Short,
    inOutModifier: Int
  )

  /**
   * ParamInfo represents the information about the parameters in a stored procedure.
   *
   * @param nativeSql
   *   the original SQL statement
   * @param dbInUse
   *   the database in use
   * @param isFunctionCall
   *   whether the SQL statement is a function call
   * @param numParameters
   *   the number of parameters in the SQL statement
   * @param parameterList
   *   a list of CallableStatementParameter representing each parameter
   * @param parameterMap
   *   a map from parameter name to CallableStatementParameter
   */
  case class ParamInfo(
    nativeSql:      String,
    dbInUse:        Option[String],
    isFunctionCall: Boolean,
    numParameters:  Int,
    parameterList:  List[CallableStatementParameter],
    parameterMap:   ListMap[String, CallableStatementParameter]
  )

  object ParamInfo:

    def apply(
      nativeSql:      String,
      database:       Option[String],
      resultSet:      ResultSetImpl,
      isFunctionCall: Boolean
    ): Fx[ParamInfo] =
      val parameterListF = resultSet.whileM[List, CallableStatementParameter] {
        for
          index           <- resultSet.getRow()
          paramName       <- resultSet.getString(4)
          procedureColumn <- resultSet.getInt(5)
          jdbcType        <- resultSet.getInt(6)
          typeName        <- resultSet.getString(7)
          precision       <- resultSet.getInt(8)
          scale           <- resultSet.getInt(10)
          nullability     <- resultSet.getShort(12)
        yield
          val inOutModifier = procedureColumn match
            case DatabaseMetaData.procedureColumnIn    => ParameterMetaData.parameterModeIn
            case DatabaseMetaData.procedureColumnInOut => ParameterMetaData.parameterModeInOut
            case DatabaseMetaData.procedureColumnOut | DatabaseMetaData.procedureColumnReturn =>
              ParameterMetaData.parameterModeOut
            case _ => ParameterMetaData.parameterModeUnknown

          val (isOutParameter, isInParameter) =
            if index - 1 == 0 && isFunctionCall then (true, false)
            else if inOutModifier == DatabaseMetaData.procedureColumnInOut then (true, true)
            else if inOutModifier == DatabaseMetaData.procedureColumnIn then (false, true)
            else if inOutModifier == DatabaseMetaData.procedureColumnOut then (true, false)
            else (false, false)

          CallableStatementParameter(
            Option(paramName),
            isInParameter,
            isOutParameter,
            index,
            jdbcType,
            Option(typeName),
            precision,
            scale,
            nullability,
            inOutModifier
          )
      }

      for
        numParameters <- resultSet.rowLength()
        parameterList <- parameterListF
      yield ParamInfo(
        nativeSql      = nativeSql,
        dbInUse        = database,
        isFunctionCall = isFunctionCall,
        numParameters  = numParameters,
        parameterList  = parameterList,
        parameterMap   = ListMap(parameterList.map(p => p.paramName.getOrElse("") -> p)*)
      )
