/**
 * Copyright (c) 2023-2026 by Takahiko Tominaga
 * This software is licensed under the MIT License (MIT).
 * For more information see LICENSE or https://opensource.org/licenses/MIT
 */

package ldbc.mysql.net.protocol

import scala.collection.immutable.{ ListMap, SortedMap }

import ldbc.sql.{ ResultSet, Statement }
import ldbc.sql.Attribute
import ldbc.sql.SQLException

import ldbc.effect.{ Concurrent, Ref }
import ldbc.effect.syntax.*
import ldbc.mysql.data.*
import ldbc.mysql.net.packet.request.*
import ldbc.mysql.net.packet.response.*
import ldbc.mysql.net.Protocol
import ldbc.mysql.telemetry.*
import ldbc.mysql.telemetry.{ DbAttributes, ErrorAttributes }
import ldbc.mysql.telemetry.{ Span, StatusCode, Tracer }
import ldbc.mysql.ResultSetImpl

/**
 * PreparedStatement for query construction at the client side.
 *
 * @param protocol
 *   Protocol is a protocol to communicate with MySQL server.
 * @param sql
 *   the SQL statement
 * @param params
 *   the parameters
 * @param F
 *   the effect type class
 * @tparam F
 *   the effect type
 */
case class ClientPreparedStatement[F[_]](
  protocol: Protocol[F],
  serverVariables:      Map[String, String],
  sql:                  String,
  params:               Ref[F, SortedMap[Int, Parameter]],
  batchedArgs:          Ref[F, Vector[String]],
  connectionClosed:     Ref[F, Boolean],
  statementClosed:      Ref[F, Boolean],
  resultSetClosed:      Ref[F, Boolean],
  currentResultSet:     Ref[F, Option[ResultSet[F]]],
  updateCount:          Ref[F, Long],
  moreResults:          Ref[F, Boolean],
  autoGeneratedKeys:    Ref[F, Int],
  lastInsertId:         Ref[F, Long],
  fetchSize:            Ref[F, Int],
  useCursorFetch:       Boolean,
  useServerPrepStmts:   Boolean,
  resultSetType:        Int             = ResultSet.TYPE_FORWARD_ONLY,
  resultSetConcurrency: Int             = ResultSet.CONCUR_READ_ONLY,
  telemetryConfig:      TelemetryConfig = TelemetryConfig.default,
  databaseMetrics:      DatabaseMetrics[F]
)(using tracer: Tracer[F], ex: Exchange[F], evF: Concurrent[F])
  extends SharedPreparedStatement[F]:

  override protected def F: Concurrent[F] = evF


  private val baseAttributes    = buildBaseAttributes(protocol)
  private val metricsAttributes = buildMetricsAttributes(protocol)

  override def executeQuery(): F[ResultSet[F]] =
    checkClosed() *> checkNullOrEmptyQuery(sql) *> exchange[F, ResultSet[F]](
      telemetryConfig.resolveSpanName(
        sql,
        TelemetrySpanName.STMT_EXECUTE_PREPARED,
        protocol.hostInfo.database,
        Some(protocol.hostInfo.host),
        Some(protocol.hostInfo.port)
      )
    ) { (span: Span[F]) =>
      params.get.flatMap { params =>
        val processedSql    = telemetryConfig.processQueryText(sql)
        val queryAttributes = baseAttributes ++ List(
          DbAttributes.DbQueryText(processedSql)
        )

        withDurationMetrics(
          span.addAttributes(queryAttributes*) *>
            protocol.resetSequenceId *>
            protocol.send(
              ComQueryPacket(buildQuery(sql, params), protocol.initialPacket.capabilityFlags, ListMap.empty)
            ) *>
            protocol.receive(ColumnsNumberPacket.decoder(protocol.initialPacket.capabilityFlags)).flatMap {
              case _: OKPacket =>
                F.pure(
                  ResultSetImpl
                    .empty(
                      protocol,
                      serverVariables,
                      protocol.initialPacket.serverVersion,
                      resultSetClosed,
                      fetchSize,
                      useCursorFetch,
                      useServerPrepStmts
                    )
                )
              case error: ERRPacket =>
                val exception = error.toException(Some(sql), None)
                span.addAttributes(error.attributes*) *>
                  span.recordException(exception, error.attributes*) *>
                  span.setStatus(StatusCode.Error, exception.getMessage) *>
                  F.raiseError(exception)
              case result: ColumnsNumberPacket =>
                for
                  columnDefinitions <-
                    protocol.repeatProcess(
                      result.size,
                      ColumnDefinitionPacket.decoder(protocol.initialPacket.capabilityFlags)
                    )
                  resultSetRow <-
                    protocol.readUntilEOF[ResultSetRowPacket](
                      textResultSetRowDecoder(protocol.initialPacket.capabilityFlags)
                    )
                  _ <- columnDefinitions.headOption match {
                         case None         => F.unit
                         case Some(column) => span.addAttribute(DbAttributes.DbCollectionName(column.table))
                       }
                  resultSet = ResultSetImpl(
                                protocol,
                                columnDefinitions,
                                resultSetRow,
                                serverVariables,
                                protocol.initialPacket.serverVersion,
                                resultSetClosed,
                                fetchSize,
                                useCursorFetch,
                                useServerPrepStmts,
                                TextColumnValueDecoder,
                                resultSetType,
                                resultSetConcurrency,
                                Some(sql)
                              )
                  _ <- currentResultSet.set(Some(resultSet))
                  _ <- databaseMetrics.recordReturnedRows(resultSetRow.size.toLong, metricsAttributes*)
                yield resultSet
            },
          metricsAttributes*
        )
      } <* params.set(SortedMap.empty)
    }

  override def executeLargeUpdate(): F[Long] =
    checkClosed() *> checkNullOrEmptyQuery(sql) *> exchange[F, Long](
      telemetryConfig.resolveSpanName(
        sql,
        TelemetrySpanName.STMT_EXECUTE_PREPARED,
        protocol.hostInfo.database,
        Some(protocol.hostInfo.host),
        Some(protocol.hostInfo.port)
      )
    ) { (span: Span[F]) =>
      params.get.flatMap { params =>
        val processedSql    = telemetryConfig.processQueryText(sql)
        val queryAttributes = baseAttributes ++ List(
          DbAttributes.DbQueryText(processedSql)
        )

        withDurationMetrics(
          span.addAttributes(queryAttributes*) *>
            protocol.resetSequenceId *>
            protocol.send(
              ComQueryPacket(buildQuery(sql, params), protocol.initialPacket.capabilityFlags, ListMap.empty)
            ) *>
            protocol.receive(GenericResponsePackets.decoder(protocol.initialPacket.capabilityFlags)).flatMap {
              case result: OKPacket => lastInsertId.set(result.lastInsertId) *> F.pure(result.affectedRows)
              case error: ERRPacket =>
                val exception = error.toException(Some(sql), None)
                span.addAttributes(error.attributes*) *>
                  span.recordException(exception, error.attributes*) *>
                  span.setStatus(StatusCode.Error, exception.getMessage) *>
                  F.raiseError(exception)
              case eof: EOFPacket =>
                val exception = new SQLException("Unexpected EOF packet")
                span.addAttribute(ErrorAttributes.ErrorType(exception.getClass.getName)) *>
                  span.recordException(exception, eof.attribute) *>
                  span.setStatus(StatusCode.Error, exception.getMessage) *>
                  F.raiseError(exception)
            },
          metricsAttributes*
        )
      } <* params.set(SortedMap.empty)
    }

  override def execute(): F[Boolean] =
    val trimmedUpper = sql.trim.toUpperCase
    if trimmedUpper.startsWith("SELECT") ||
      trimmedUpper.startsWith("SHOW") ||
      trimmedUpper.startsWith("DESC") ||
      trimmedUpper.startsWith("EXPLAIN") ||
      trimmedUpper.startsWith("WITH") ||
      trimmedUpper.startsWith("TABLE") ||
      trimmedUpper.startsWith("OPTIMIZE") ||
      trimmedUpper.startsWith("CHECK") ||
      trimmedUpper.startsWith("REPAIR") ||
      trimmedUpper.startsWith("ANALYZE") ||
      trimmedUpper.startsWith("(")
    then
      executeQuery().flatMap {
        case resultSet: (ResultSetImpl[F] @unchecked) => resultSet.hasRows()
        case _                        => F.pure(false)
      }
    else executeUpdate().map(_ => false)

  override def addBatch(): F[Unit] =
    checkClosed() *> checkNullOrEmptyQuery(sql) *> params.get.flatMap { params =>
      batchedArgs.update(_ :+ buildBatchQuery(sql, params))
    } *> params.set(SortedMap.empty)

  override def clearBatch(): F[Unit] = batchedArgs.set(Vector.empty)

  override def executeLargeBatch(): F[Array[Long]] =
    checkClosed() *> checkNullOrEmptyQuery(sql) *> (
      sql.trim.toLowerCase match
        case q if q.startsWith("insert") =>
          exchange[F, Array[Long]](TelemetrySpanName.STMT_EXECUTE_BATCH_PREPARED) { (span: Span[F]) =>
            protocol.resetSequenceId *>
              batchedArgs.get.flatMap { args =>
                val batchAttributes = baseAttributes ++
                  List(DbAttributes.DbOperationName(TelemetryAttribute.SqlOperation.BATCH)) ++
                  TelemetryAttribute.dbOperationBatchSize(args.length).toList

                if args.isEmpty then F.pure(Array.empty)
                else
                  withDurationMetrics(
                    span.addAttributes(batchAttributes*) *>
                      protocol.resetSequenceId *>
                      protocol.send(
                        ComQueryPacket(
                          sql.split("VALUES").head + " VALUES" + args.mkString(","),
                          protocol.initialPacket.capabilityFlags,
                          ListMap.empty
                        )
                      ) *>
                      protocol
                        .receive(GenericResponsePackets.decoder(protocol.initialPacket.capabilityFlags))
                        .flatMap {
                          case _: OKPacket      => F.pure(Array.fill(args.length)(Statement.SUCCESS_NO_INFO.toLong))
                          case error: ERRPacket =>
                            val exception = error.toException(Some(sql), None)
                            span.addAttributes(error.attributes*) *>
                              span.recordException(exception, error.attributes*) *>
                              span.setStatus(StatusCode.Error, exception.getMessage) *>
                              F.raiseError(exception)
                          case eof: EOFPacket =>
                            val exception = new SQLException("Unexpected EOF packet")
                            span.addAttribute(ErrorAttributes.ErrorType(exception.getClass.getName)) *>
                              span.recordException(exception, eof.attribute) *>
                              span.setStatus(StatusCode.Error, exception.getMessage) *>
                              F.raiseError(exception)
                        },
                    metricsAttributes*
                  )
              }
          } <* params.set(SortedMap.empty) <* batchedArgs.set(Vector.empty)
        case q if q.startsWith("update") || q.startsWith("delete") =>
          protocol.resetSequenceId *>
            protocol.comSetOption(EnumMySQLSetOption.MYSQL_OPTION_MULTI_STATEMENTS_ON) *>
            exchange[F, Array[Long]](TelemetrySpanName.STMT_EXECUTE_BATCH_PREPARED) { (span: Span[F]) =>
              protocol.resetSequenceId *>
                batchedArgs.get.flatMap { args =>
                  val batchAttributes = baseAttributes ++
                    List(DbAttributes.DbOperationName(TelemetryAttribute.SqlOperation.BATCH)) ++
                    TelemetryAttribute.dbOperationBatchSize(args.length).toList

                  if args.isEmpty then F.pure(Array.empty)
                  else
                    withDurationMetrics(
                      span.addAttributes(batchAttributes*) *>
                        protocol.resetSequenceId *>
                        protocol.send(
                          ComQueryPacket(
                            args.mkString(";"),
                            protocol.initialPacket.capabilityFlags,
                            ListMap.empty
                          )
                        ) *>
                        args
                          .foldLeft(F.pure(Vector.empty[Long])) { ($acc, _) =>
                            for
                              acc    <- $acc
                              result <-
                                protocol
                                  .receive(GenericResponsePackets.decoder(protocol.initialPacket.capabilityFlags))
                                  .flatMap {
                                    case result: OKPacket =>
                                      lastInsertId.set(result.lastInsertId) *> F.pure(acc :+ result.affectedRows)
                                    case error: ERRPacket =>
                                      val exception = error.toException("Failed to execute batch", acc)
                                      span.addAttributes(error.attributes*) *>
                                        span.recordException(exception, error.attributes*) *>
                                        span.setStatus(StatusCode.Error, exception.getMessage) *>
                                        F.raiseError(exception)
                                    case eof: EOFPacket =>
                                      val exception = new SQLException("Unexpected EOF packet")
                                      span.addAttribute(ErrorAttributes.ErrorType(exception.getClass.getName)) *>
                                        span.recordException(exception, eof.attribute) *>
                                        span.setStatus(StatusCode.Error, exception.getMessage) *>
                                        F.raiseError(exception)
                                  }
                            yield result
                          }
                          .map(_.toArray),
                      metricsAttributes*
                    )
                }
            } <*
            protocol.resetSequenceId <*
            protocol.comSetOption(EnumMySQLSetOption.MYSQL_OPTION_MULTI_STATEMENTS_OFF) <*
            params.set(SortedMap.empty) <*
            batchedArgs.set(Vector.empty)
        case _ =>
          F.raiseError(
            new IllegalArgumentException("The batch query must be an INSERT, UPDATE, or DELETE statement.")
          )
    )

  override def close(): F[Unit] = statementClosed.set(true) *> resultSetClosed.set(true)
