/**
 * Copyright (c) 2023-2026 by Takahiko Tominaga
 * This software is licensed under the MIT License (MIT).
 * For more information see LICENSE or https://opensource.org/licenses/MIT
 */

package ldbc.mysql.net.protocol

import ldbc.sql.SQLException
import scala.collection.immutable.{ ListMap, SortedMap }

import ldbc.fx.{ Fx, Ref }
import ldbc.fx.syntax.*

import ldbc.mysql.telemetry.{ DbAttributes, ErrorAttributes }
import ldbc.mysql.telemetry.{ Span, StatusCode, Tracer }
import ldbc.sql.Attribute

import ldbc.sql.{ ResultSet, Statement }

import ldbc.mysql.{ ResultSetImpl, StreamingResultSet }
import ldbc.mysql.data.*
import ldbc.mysql.net.packet.request.*
import ldbc.mysql.net.packet.response.*
import ldbc.mysql.net.Protocol
import ldbc.mysql.telemetry.*

/**
 * PreparedStatement for query construction at the server side.
 *
 * @param protocol
 *   Protocol is a protocol to communicate with MySQL server.
 * @param statementId
 *   the statement id
 * @param sql
 *   the SQL statement
 * @param params
 *   the parameters
 * @tparam F
 *   The effect type
 */
case class ServerPreparedStatement(
  protocol:             Protocol,
  serverVariables:      Map[String, String],
  statementId:          Long,
  sql:                  String,
  params:               Ref[SortedMap[Int, Parameter]],
  batchedArgs:          Ref[Vector[String]],
  connectionClosed:     Ref[Boolean],
  statementClosed:      Ref[Boolean],
  resultSetClosed:      Ref[Boolean],
  currentResultSet:     Ref[Option[ResultSet[Fx]]],
  updateCount:          Ref[Long],
  moreResults:          Ref[Boolean],
  autoGeneratedKeys:    Ref[Int],
  lastInsertId:         Ref[Long],
  fetchSize:            Ref[Int],
  useCursorFetch:       Boolean,
  useServerPrepStmts:   Boolean,
  resultSetType:        Int             = ResultSet.TYPE_FORWARD_ONLY,
  resultSetConcurrency: Int             = ResultSet.CONCUR_READ_ONLY,
  telemetryConfig:      TelemetryConfig = TelemetryConfig.default,
  databaseMetrics:      DatabaseMetrics
)(using Tracer, Exchange)
  extends SharedPreparedStatement:

  private val baseAttributes    = buildBaseAttributes(protocol)
  private val metricsAttributes = buildMetricsAttributes(protocol)

  private def buildResultSet(
    columnDefinitions: Vector[ColumnDefinitionPacket],
    records:           Vector[ResultSetRowPacket]
  ): ResultSet[Fx] =
    if useCursorFetch then
      StreamingResultSet(
        protocol,
        statementId,
        columnDefinitions,
        records,
        serverVariables,
        protocol.initialPacket.serverVersion,
        resultSetClosed,
        fetchSize,
        useCursorFetch,
        useServerPrepStmts,
        BinaryColumnValueDecoder,
        resultSetType,
        resultSetConcurrency,
        Some(sql)
      )
    else
      ResultSetImpl(
        protocol,
        columnDefinitions,
        records,
        serverVariables,
        protocol.initialPacket.serverVersion,
        resultSetClosed,
        fetchSize,
        useCursorFetch,
        useServerPrepStmts,
        BinaryColumnValueDecoder,
        resultSetType,
        resultSetConcurrency,
        Some(sql)
      )

  override def executeQuery(): Fx[ResultSet[Fx]] =
    checkClosed() *> checkNullOrEmptyQuery(sql) *> exchange[ResultSet[Fx]](
      telemetryConfig.resolveSpanName(
        sql,
        TelemetrySpanName.STMT_EXECUTE_PREPARED,
        protocol.hostInfo.database,
        Some(protocol.hostInfo.host),
        Some(protocol.hostInfo.port)
      )
    ) { (span: Span) =>
      val processedSql    = telemetryConfig.processQueryText(sql)
      val queryAttributes = baseAttributes ++ List(
        DbAttributes.DbQueryText(processedSql)
      )

      withDurationMetrics(
        (for
          parameter   <- params.get
          _           <- span.addAttributes(queryAttributes*)
          columnCount <-
            protocol.resetSequenceId *>
              protocol.send(
                ComStmtExecutePacket(statementId, parameter, resultSetType, resultSetConcurrency, useCursorFetch)
              ) *>
              protocol.receive(ColumnsNumberPacket.decoder(protocol.initialPacket.capabilityFlags)).flatMap {
                case _: OKPacket      => Fx.pure(ColumnsNumberPacket(0))
                case error: ERRPacket =>
                  val exception = error.toException(Some(sql), None)
                  span.addAttributes(error.attributes*) *>
                    span.recordException(exception, error.attributes*) *>
                    span.setStatus(StatusCode.Error, exception.getMessage) *>
                    Fx.raiseError(exception)
                case result: ColumnsNumberPacket => Fx.pure(result)
              }
          columnDefinitions <-
            protocol.repeatProcess(
              columnCount.size,
              ColumnDefinitionPacket.decoder(protocol.initialPacket.capabilityFlags)
            )
          resultSetRow <-
            protocol.readUntilEOF[ResultSetRowPacket](
              binaryResultSetRowDecoder(protocol.initialPacket.capabilityFlags)
            )
          _ <- columnDefinitions.headOption match {
                 case None         => Fx.unit
                 case Some(column) => span.addAttribute(DbAttributes.DbCollectionName(column.table))
               }
          _ <- params.set(SortedMap.empty)
          resultSet = buildResultSet(columnDefinitions, resultSetRow)
          _ <- currentResultSet.set(Some(resultSet))
          _ <- databaseMetrics.recordReturnedRows(resultSetRow.size.toLong, metricsAttributes*)
        yield resultSet),
        metricsAttributes*
      )
    }

  override def executeLargeUpdate(): Fx[Long] =
    checkClosed() *> checkNullOrEmptyQuery(sql) *> exchange[Long](
      telemetryConfig.resolveSpanName(
        sql,
        TelemetrySpanName.STMT_EXECUTE_PREPARED,
        protocol.hostInfo.database,
        Some(protocol.hostInfo.host),
        Some(protocol.hostInfo.port)
      )
    ) { (span: Span) =>
      params.get.flatMap { params =>
        val processedSql    = telemetryConfig.processQueryText(sql)
        val queryAttributes = baseAttributes ++ List(
          DbAttributes.DbQueryText(processedSql)
        )

        withDurationMetrics(
          span.addAttributes(queryAttributes*) *>
            protocol.resetSequenceId *>
            protocol.send(
              ComStmtExecutePacket(statementId, params, resultSetType, resultSetConcurrency, useCursorFetch)
            ) *>
            protocol.receive(GenericResponsePackets.decoder(protocol.initialPacket.capabilityFlags)).flatMap {
              case result: OKPacket => lastInsertId.set(result.lastInsertId) *> Fx.pure(result.affectedRows)
              case error: ERRPacket =>
                val exception = error.toException(Some(sql), None)
                span.addAttributes(error.attributes*) *>
                  span.recordException(exception, error.attributes*) *>
                  span.setStatus(StatusCode.Error, exception.getMessage) *>
                  Fx.raiseError(exception)
              case eof: EOFPacket =>
                val exception = new SQLException("Unexpected EOF packet")
                span.addAttribute(ErrorAttributes.ErrorType(exception.getClass.getName)) *>
                  span.recordException(exception, eof.attribute) *>
                  span.setStatus(StatusCode.Error, exception.getMessage) *>
                  Fx.raiseError(exception)
            },
          metricsAttributes*
        )
      } <* params.set(SortedMap.empty)
    }

  override def execute(): Fx[Boolean] =
    val trimmedUpper = sql.trim.toUpperCase
    if trimmedUpper.startsWith("SELECT") ||
      trimmedUpper.startsWith("SHOW") ||
      trimmedUpper.startsWith("DESC") ||
      trimmedUpper.startsWith("EXPLAIN") ||
      trimmedUpper.startsWith("WITH") ||
      trimmedUpper.startsWith("TABLE") ||
      trimmedUpper.startsWith("OPTIMIZE") ||
      trimmedUpper.startsWith("CHECK") ||
      trimmedUpper.startsWith("REPAIR") ||
      trimmedUpper.startsWith("ANALYZE") ||
      trimmedUpper.startsWith("(")
    then
      executeQuery().flatMap {
        case resultSet: ResultSetImpl => resultSet.hasRows()
        case _                           => Fx.pure(false)
      }
    else executeUpdate().map(_ => false)

  override def addBatch(): Fx[Unit] =
    checkClosed() *> checkNullOrEmptyQuery(sql) *> params.get.flatMap { params =>
      batchedArgs.update(_ :+ buildBatchQuery(sql, params))
    } *> params.set(SortedMap.empty)

  override def clearBatch(): Fx[Unit] = batchedArgs.set(Vector.empty)

  override def executeLargeBatch(): Fx[Array[Long]] =
    checkClosed() *> checkNullOrEmptyQuery(sql) *> (
      sql.trim.toLowerCase match
        case q if q.startsWith("insert") =>
          exchange[Array[Long]](TelemetrySpanName.STMT_EXECUTE_BATCH_PREPARED) { (span: Span) =>
            protocol.resetSequenceId *>
              batchedArgs.get.flatMap { args =>
                val batchAttributes = baseAttributes ++
                  List(DbAttributes.DbOperationName(TelemetryAttribute.SqlOperation.BATCH)) ++
                  TelemetryAttribute.dbOperationBatchSize(args.length).toList

                if args.isEmpty then Fx.pure(Array.empty)
                else
                  withDurationMetrics(
                    span.addAttributes(batchAttributes*) *>
                      protocol.resetSequenceId *>
                      protocol.send(
                        ComQueryPacket(
                          sql.split("VALUES").head + " VALUES" + args.mkString(","),
                          protocol.initialPacket.capabilityFlags,
                          ListMap.empty
                        )
                      ) *>
                      protocol
                        .receive(GenericResponsePackets.decoder(protocol.initialPacket.capabilityFlags))
                        .flatMap {
                          case _: OKPacket      => Fx.pure(Array.fill(args.length)(Statement.SUCCESS_NO_INFO.toLong))
                          case error: ERRPacket =>
                            val exception = error.toException(Some(sql), None)
                            span.addAttributes(error.attributes*) *>
                              span.recordException(exception, error.attributes*) *>
                              span.setStatus(StatusCode.Error, exception.getMessage) *>
                              Fx.raiseError(exception)
                          case eof: EOFPacket =>
                            val exception = new SQLException("Unexpected EOF packet")
                            span.addAttribute(ErrorAttributes.ErrorType(exception.getClass.getName)) *>
                              span.recordException(exception, eof.attribute) *>
                              span.setStatus(StatusCode.Error, exception.getMessage) *>
                              Fx.raiseError(exception)
                        },
                    metricsAttributes*
                  )
              }
          } <* params.set(SortedMap.empty) <* batchedArgs.set(Vector.empty)
        case q if q.startsWith("update") || q.startsWith("delete") =>
          protocol.resetSequenceId *>
            protocol.comSetOption(EnumMySQLSetOption.MYSQL_OPTION_MULTI_STATEMENTS_ON) *>
            exchange[Array[Long]](TelemetrySpanName.STMT_EXECUTE_BATCH_PREPARED) { (span: Span) =>
              protocol.resetSequenceId *>
                batchedArgs.get.flatMap { args =>
                  val batchAttributes = baseAttributes ++
                    List(DbAttributes.DbOperationName(TelemetryAttribute.SqlOperation.BATCH)) ++
                    TelemetryAttribute.dbOperationBatchSize(args.length).toList

                  if args.isEmpty then Fx.pure(Array.empty)
                  else
                    withDurationMetrics(
                      span.addAttributes(batchAttributes*) *>
                        protocol.resetSequenceId *>
                        protocol.send(
                          ComQueryPacket(
                            args.mkString(";"),
                            protocol.initialPacket.capabilityFlags,
                            ListMap.empty
                          )
                        ) *>
                        args
                          .foldLeft(Fx.pure(Vector.empty[Long])) { ($acc, _) =>
                            for
                              acc    <- $acc
                              result <-
                                protocol
                                  .receive(GenericResponsePackets.decoder(protocol.initialPacket.capabilityFlags))
                                  .flatMap {
                                    case result: OKPacket =>
                                      lastInsertId.set(result.lastInsertId) *> Fx.pure(acc :+ result.affectedRows)
                                    case error: ERRPacket =>
                                      val exception = error.toException("Failed to execute batch", acc)
                                      span.addAttributes(error.attributes*) *>
                                        span.recordException(exception, error.attributes*) *>
                                        span.setStatus(StatusCode.Error, exception.getMessage) *>
                                        Fx.raiseError(exception)
                                    case eof: EOFPacket =>
                                      val exception = new SQLException("Unexpected EOF packet")
                                      span.addAttribute(ErrorAttributes.ErrorType(exception.getClass.getName)) *>
                                        span.recordException(exception, eof.attribute) *>
                                        span.setStatus(StatusCode.Error, exception.getMessage) *>
                                        Fx.raiseError(exception)
                                  }
                            yield result
                          }
                          .map(_.toArray),
                      metricsAttributes*
                    )
                }
            } <*
            protocol.resetSequenceId <*
            protocol.comSetOption(EnumMySQLSetOption.MYSQL_OPTION_MULTI_STATEMENTS_OFF) <*
            params.set(SortedMap.empty) <*
            batchedArgs.set(Vector.empty)
        case _ =>
          Fx.raiseError(
            new IllegalArgumentException("The batch query must be an INSERT, UPDATE, or DELETE statement.")
          )
    )

  override def close(): Fx[Unit] =
    exchange[Unit](TelemetrySpanName.STMT_DEALLOCATE_PREPARED) { (span: Span) =>
      val closeAttributes = baseAttributes ++ List(
        DbAttributes.DbOperationName("CLOSE")
      )

      span.addAttributes(closeAttributes*) *> protocol.resetSequenceId *> protocol.send(
        ComStmtClosePacket(statementId)
      ) *> statementClosed.set(
        true
      ) *> resultSetClosed.set(true)
    }
