/**
 * Copyright (c) 2023-2026 by Takahiko Tominaga
 * This software is licensed under the MIT License (MIT).
 * For more information see LICENSE or https://opensource.org/licenses/MIT
 */

package ldbc.mysql.net.protocol

import scala.collection.immutable.{ ListMap, SortedMap }

import ldbc.sql.{ PreparedStatement, ResultSet, Statement }
import ldbc.sql.Attribute
import ldbc.sql.SQLException

import ldbc.fx.{ Fx, Ref }
import ldbc.fx.syntax.*
import ldbc.mysql.data.*
import ldbc.mysql.net.packet.request.*
import ldbc.mysql.net.packet.response.*
import ldbc.mysql.net.Protocol
import ldbc.mysql.telemetry.*
import ldbc.mysql.telemetry.{ DbAttributes, ErrorAttributes, ServerAttributes }
import ldbc.mysql.telemetry.{ Span, StatusCode, Tracer }
import ldbc.mysql.util.StringHelper
import ldbc.mysql.ResultSetImpl

private[ldbc] case class StatementImpl(
  protocol:             Protocol,
  serverVariables:      Map[String, String],
  batchedArgs:          Ref[Vector[String]],
  connectionClosed:     Ref[Boolean],
  statementClosed:      Ref[Boolean],
  resultSetClosed:      Ref[Boolean],
  currentResultSet:     Ref[Option[ResultSet[Fx]]],
  updateCount:          Ref[Long],
  moreResults:          Ref[Boolean],
  autoGeneratedKeys:    Ref[Int],
  lastInsertId:         Ref[Long],
  fetchSize:            Ref[Int],
  useCursorFetch:       Boolean,
  useServerPrepStmts:   Boolean,
  resultSetType:        Int             = ResultSet.TYPE_FORWARD_ONLY,
  resultSetConcurrency: Int             = ResultSet.CONCUR_READ_ONLY,
  telemetryConfig:      TelemetryConfig = TelemetryConfig.default,
  databaseMetrics:      DatabaseMetrics
)(using Tracer, Exchange)
  extends StatementImpl.ShareStatement:

  private val baseAttributes    = buildBaseAttributes(protocol)
  private val metricsAttributes = buildMetricsAttributes(protocol)

  private def simpleQueryRun(sql: String): Fx[ResultSet[Fx]] =
    exchange[ResultSet[Fx]](
      telemetryConfig.resolveSpanName(
        sql,
        TelemetrySpanName.STMT_EXECUTE,
        protocol.hostInfo.database,
        Some(protocol.hostInfo.host),
        Some(protocol.hostInfo.port)
      )
    ) { (span: Span) =>
      val processedSql    = telemetryConfig.processQueryText(sql)
      val queryAttributes = baseAttributes ++ List(
        DbAttributes.DbQueryText(processedSql)
      )

      withDurationMetrics(
        span.addAttributes(queryAttributes*) *>
          protocol.resetSequenceId *>
          protocol.send(ComQueryPacket(sql, protocol.initialPacket.capabilityFlags, ListMap.empty)) *>
          protocol.receive(ColumnsNumberPacket.decoder(protocol.initialPacket.capabilityFlags)).flatMap {
            case _: OKPacket =>
              for
                resultSet <- Fx.pure(
                               ResultSetImpl
                                 .empty(
                                   protocol,
                                   serverVariables,
                                   protocol.initialPacket.serverVersion,
                                   resultSetClosed,
                                   fetchSize,
                                   useCursorFetch,
                                   useServerPrepStmts
                                 )
                             )
                _ <- currentResultSet.set(Some(resultSet))
              yield resultSet
            case error: ERRPacket =>
              val exception = error.toException(Some(sql), None)
              span.addAttributes(error.attributes*) *>
                span.recordException(exception, error.attributes*) *>
                span.setStatus(StatusCode.Error, exception.getMessage) *>
                Fx.raiseError(exception)
            case result: ColumnsNumberPacket =>
              for
                columnDefinitions <-
                  protocol.repeatProcess(
                    result.size,
                    ColumnDefinitionPacket.decoder(protocol.initialPacket.capabilityFlags)
                  )
                resultSetRow <-
                  protocol.readUntilEOF[ResultSetRowPacket](
                    textResultSetRowDecoder(protocol.initialPacket.capabilityFlags)
                  )
                _ <- columnDefinitions.headOption match {
                       case None         => Fx.unit
                       case Some(column) => span.addAttribute(DbAttributes.DbCollectionName(column.table))
                     }
                resultSet = ResultSetImpl(
                              protocol,
                              columnDefinitions,
                              resultSetRow,
                              serverVariables,
                              protocol.initialPacket.serverVersion,
                              resultSetClosed,
                              fetchSize,
                              useCursorFetch,
                              useServerPrepStmts,
                              TextColumnValueDecoder,
                              resultSetType,
                              resultSetConcurrency,
                              Some(sql)
                            )
                _ <- currentResultSet.set(Some(resultSet))
                _ <- databaseMetrics.recordReturnedRows(resultSetRow.size.toLong, metricsAttributes*)
              yield resultSet
          },
        metricsAttributes*
      )
    }

  private def buildServerPreparedStatement(sql: String): Fx[PreparedStatement[Fx]] =
    for
      result <- protocol.resetSequenceId *> protocol.send(ComStmtPreparePacket(sql)) *>
                  protocol.receive(ComStmtPrepareOkPacket.decoder(protocol.initialPacket.capabilityFlags)).flatMap {
                    case error: ERRPacket           => Fx.raiseError(error.toException(Some(sql), None))
                    case ok: ComStmtPrepareOkPacket => Fx.pure(ok)
                  }
      _ <- protocol.repeatProcess(
             result.numParams,
             ColumnDefinitionPacket.decoder(protocol.initialPacket.capabilityFlags)
           )
      _ <- protocol.repeatProcess(
             result.numColumns,
             ColumnDefinitionPacket.decoder(protocol.initialPacket.capabilityFlags)
           )
      params            <- Ref.of(SortedMap.empty[Int, Parameter])
      batchedArgs       <- Ref.of(Vector.empty[String])
      statementClosed   <- Ref.of[Boolean](false)
      resultSetClosed   <- Ref.of[Boolean](false)
      currentResultSet  <- Ref.of[Option[ResultSet[Fx]]](None)
      updateCount       <- Ref.of(-1L)
      moreResults       <- Ref.of(false)
      autoGeneratedKeys <- Ref.of(Statement.NO_GENERATED_KEYS)
      lastInsertId      <- Ref.of(0L)
    yield ServerPreparedStatement(
      protocol,
      serverVariables,
      result.statementId,
      sql,
      params,
      batchedArgs,
      connectionClosed,
      statementClosed,
      resultSetClosed,
      currentResultSet,
      updateCount,
      moreResults,
      autoGeneratedKeys,
      lastInsertId,
      fetchSize,
      useCursorFetch,
      useServerPrepStmts,
      resultSetType,
      resultSetConcurrency,
      telemetryConfig,
      databaseMetrics
    )

  private def buildClientPreparedStatement(sql: String): Fx[PreparedStatement[Fx]] =
    for
      params            <- Ref.of(SortedMap.empty[Int, Parameter])
      batchedArgs       <- Ref.of(Vector.empty[String])
      statementClosed   <- Ref.of[Boolean](false)
      resultSetClosed   <- Ref.of[Boolean](false)
      currentResultSet  <- Ref.of[Option[ResultSet[Fx]]](None)
      updateCount       <- Ref.of(-1L)
      moreResults       <- Ref.of(false)
      autoGeneratedKeys <- Ref.of(Statement.NO_GENERATED_KEYS)
      lastInsertId      <- Ref.of(0L)
    yield ClientPreparedStatement(
      protocol,
      serverVariables,
      sql,
      params,
      batchedArgs,
      connectionClosed,
      statementClosed,
      resultSetClosed,
      currentResultSet,
      updateCount,
      moreResults,
      autoGeneratedKeys,
      lastInsertId,
      fetchSize,
      useCursorFetch,
      useServerPrepStmts,
      resultSetType,
      resultSetConcurrency,
      telemetryConfig,
      databaseMetrics
    )

  private def preparedQueryRun(sql: String): Fx[ResultSet[Fx]] =
    for
      preparedStatement <- Fx.pure(useServerPrepStmts)
                             .ifM[PreparedStatement[Fx]](
                               buildServerPreparedStatement(sql),
                               buildClientPreparedStatement(sql)
                             )
      resultSet <- preparedStatement.executeQuery()
    yield resultSet

  override def executeQuery(sql: String): Fx[ResultSet[Fx]] =
    checkClosed() *> checkNullOrEmptyQuery(sql) *>
      useServerFetch().ifM(
        preparedQueryRun(sql),
        simpleQueryRun(sql)
      )

  override def executeUpdate(sql: String): Fx[Int] =
    executeLargeUpdate(sql).map(_.toInt)

  override def executeLargeUpdate(sql: String): Fx[Long] =
    checkClosed() *> checkNullOrEmptyQuery(sql) *> exchange[Long](
      telemetryConfig.resolveSpanName(
        sql,
        TelemetrySpanName.STMT_EXECUTE,
        protocol.hostInfo.database,
        Some(protocol.hostInfo.host),
        Some(protocol.hostInfo.port)
      )
    ) { (span: Span) =>
      val processedSql    = telemetryConfig.processQueryText(sql)
      val queryAttributes = baseAttributes ++ List(
        DbAttributes.DbQueryText(processedSql)
      )

      withDurationMetrics(
        span.addAttributes(queryAttributes*) *>
          protocol.resetSequenceId *> (
            protocol.send(ComQueryPacket(sql, protocol.initialPacket.capabilityFlags, ListMap.empty)) *>
              protocol.receive(GenericResponsePackets.decoder(protocol.initialPacket.capabilityFlags)).flatMap {
                case result: OKPacket =>
                  lastInsertId.set(result.lastInsertId) *> updateCount.updateAndGet(_ => result.affectedRows)
                case error: ERRPacket =>
                  val exception = error.toException(Some(sql), None)
                  span.addAttributes(error.attributes*) *>
                    span.recordException(exception, error.attributes*) *>
                    span.setStatus(StatusCode.Error, exception.getMessage) *>
                    Fx.raiseError(exception)
                case eof: EOFPacket =>
                  val exception = new SQLException("Unexpected EOF packet")
                  span.addAttribute(ErrorAttributes.ErrorType(exception.getClass.getName)) *>
                    span.recordException(exception, eof.attribute) *>
                    span.setStatus(StatusCode.Error, exception.getMessage) *>
                    Fx.raiseError(exception)
              }
          ),
        metricsAttributes*
      )
    }

  override def close(): Fx[Unit] = statementClosed.set(true) *> resultSetClosed.set(true)

  override def execute(sql: String): Fx[Boolean] =
    checkClosed() *> checkNullOrEmptyQuery(sql) *> {
      val trimmedUpper = sql.trim.toUpperCase
      if trimmedUpper.startsWith("SELECT") ||
        trimmedUpper.startsWith("SHOW") ||
        trimmedUpper.startsWith("DESC") ||
        trimmedUpper.startsWith("EXPLAIN") ||
        trimmedUpper.startsWith("WITH") ||
        trimmedUpper.startsWith("TABLE") ||
        trimmedUpper.startsWith("OPTIMIZE") ||
        trimmedUpper.startsWith("CHECK") ||
        trimmedUpper.startsWith("REPAIR") ||
        trimmedUpper.startsWith("ANALYZE") ||
        trimmedUpper.startsWith("(")
      then
        executeQuery(sql).flatMap {
          case resultSet: ResultSetImpl => resultSet.hasRows()
          case _                        => Fx.pure(false)
        }
      else executeUpdate(sql).map(_ => false)
    }

  override def addBatch(sql: String): Fx[Unit] = batchedArgs.update(_ :+ sql)

  override def clearBatch(): Fx[Unit] = batchedArgs.set(Vector.empty)

  override def executeLargeBatch(): Fx[Array[Long]] =
    checkClosed() *> protocol.resetSequenceId *>
      protocol.comSetOption(EnumMySQLSetOption.MYSQL_OPTION_MULTI_STATEMENTS_ON) *>
      exchange[Array[Long]](TelemetrySpanName.STMT_EXECUTE_BATCH) { (span: Span) =>
        batchedArgs.get.flatMap { args =>
          val batchAttributes = baseAttributes ++
            List(DbAttributes.DbOperationName(TelemetryAttribute.SqlOperation.BATCH)) ++
            TelemetryAttribute.dbOperationBatchSize(args.length).toList

          if args.isEmpty then Fx.pure(Array.empty)
          else
            withDurationMetrics(
              span.addAttributes(batchAttributes*) *>
                protocol.resetSequenceId *>
                protocol.send(
                  ComQueryPacket(args.mkString(";"), protocol.initialPacket.capabilityFlags, ListMap.empty)
                ) *>
                args
                  .foldLeft(Fx.pure(Vector.empty[Long])) { ($acc, _) =>
                    for
                      acc    <- $acc
                      result <-
                        protocol
                          .receive(GenericResponsePackets.decoder(protocol.initialPacket.capabilityFlags))
                          .flatMap {
                            case result: OKPacket =>
                              lastInsertId.set(result.lastInsertId) *> Fx.pure(acc :+ result.affectedRows)
                            case error: ERRPacket =>
                              val exception = error.toException("Failed to execute batch", acc)
                              span.addAttributes(error.attributes*) *>
                                span.recordException(exception, error.attributes*) *>
                                span.setStatus(StatusCode.Error, exception.getMessage) *>
                                Fx.raiseError(exception)
                            case eof: EOFPacket =>
                              val exception = new SQLException("Unexpected EOF packet")
                              span.addAttribute(ErrorAttributes.ErrorType(exception.getClass.getName)) *>
                                span.recordException(exception, eof.attribute) *>
                                span.setStatus(StatusCode.Error, exception.getMessage) *>
                                Fx.raiseError(exception)
                          }
                    yield result
                  }
                  .map(_.toArray),
              metricsAttributes*
            )
        }
      } <* protocol.resetSequenceId <* protocol.comSetOption(
        EnumMySQLSetOption.MYSQL_OPTION_MULTI_STATEMENTS_OFF
      ) <* clearBatch()

object StatementImpl:

  private[ldbc] trait ShareStatement extends Statement[Fx]:

    def protocol:          Protocol
    def serverVariables:   Map[String, String]
    def statementClosed:   Ref[Boolean]
    def connectionClosed:  Ref[Boolean]
    def resultSetClosed:   Ref[Boolean]
    def currentResultSet:  Ref[Option[ResultSet[Fx]]]
    def updateCount:       Ref[Long]
    def moreResults:       Ref[Boolean]
    def autoGeneratedKeys: Ref[Int]
    def lastInsertId:      Ref[Long]

    def fetchSize:          Ref[Int]
    def useCursorFetch:     Boolean
    def useServerPrepStmts: Boolean
    def resultSetType:      Int
    def databaseMetrics:    DatabaseMetrics

    override def getGeneratedKeys(): Fx[ResultSet[Fx]] =
      autoGeneratedKeys.get.flatMap {
        case Statement.RETURN_GENERATED_KEYS =>
          for
            lastInsertId <- lastInsertId.get
            record    = ResultSetRowPacket.fromStrings(Some(lastInsertId.toString))
            resultSet = ResultSetImpl(
                          protocol,
                          Vector(new ColumnDefinitionPacket:
                            override def table:      String                     = ""
                            override def name:       String                     = "GENERATED_KEYS"
                            override def columnType: ColumnDataType             = ColumnDataType.MYSQL_TYPE_LONGLONG
                            override def flags:      Seq[ColumnDefinitionFlags] = Seq.empty
                            override def charset:    String                     = "UTF-8"),
                          Vector(record),
                          serverVariables,
                          protocol.initialPacket.serverVersion,
                          resultSetClosed,
                          fetchSize,
                          useCursorFetch,
                          useServerPrepStmts,
                          TextColumnValueDecoder
                        )
            _ <- currentResultSet.set(Some(resultSet))
          yield resultSet
        case Statement.NO_GENERATED_KEYS =>
          Fx.raiseError(
            new SQLException(
              "Generated keys not requested. You need to specify Statement.RETURN_GENERATED_KEYS to Statement.executeUpdate(), Statement.executeLargeUpdate() or Connection.prepareStatement()."
            )
          )
      }

    override def getResultSet():        Fx[Option[ResultSet[Fx]]] = checkClosed() *> currentResultSet.get
    override def getUpdateCount():      Fx[Int]                   = checkClosed() *> updateCount.get.map(_.toInt)
    override def getLargeUpdateCount(): Fx[Long]                  = checkClosed() *> updateCount.get
    override def getMoreResults():      Fx[Boolean]               = checkClosed() *> moreResults.get

    override def executeUpdate(sql: String, autoGeneratedKeys: Int): Fx[Int] =
      this.autoGeneratedKeys.set(autoGeneratedKeys) *> executeUpdate(sql)

    override def executeLargeUpdate(sql: String, autoGeneratedKeys: Int): Fx[Long] =
      this.autoGeneratedKeys.set(autoGeneratedKeys) *> executeLargeUpdate(sql)

    override def execute(sql: String, autoGeneratedKeys: Int): Fx[Boolean] =
      this.autoGeneratedKeys.set(autoGeneratedKeys) *> execute(sql)

    override def isClosed(): Fx[Boolean] =
      for
        connClosed <- connectionClosed.get
        stmtClosed <- statementClosed.get
      yield connClosed || stmtClosed

    override def executeBatch(): Fx[Array[Int]] = executeLargeBatch().map(_.map(_.toInt))

    override def setFetchSize(rows: Int): Fx[Unit] = fetchSize.set(rows)

    override def getFetchSize(): Fx[Int] = fetchSize.get

    override def enquoteLiteral(value: String): Fx[String] =
      if value == null then Fx.pure("NULL")
      else Fx.pure(StringHelper.enquoteLiteral(value, ansiQuotesEnabled, backslashEscapesEnabled))

    override def enquoteIdentifier(identifier: String, alwaysQuote: Boolean): Fx[String] =
      if identifier == null then Fx.raiseError(new SQLException("Value 'null' is not a valid identifier."))
      else if StringHelper.isSimpleIdentifier(identifier) then
        val quoteChar = if ansiQuotesEnabled then '"' else '`'
        Fx.pure(if alwaysQuote then s"$quoteChar$identifier$quoteChar" else identifier)
      else Fx.pure(StringHelper.enquoteIdentifier(identifier, ansiQuotesEnabled))

    override def enquoteNCharLiteral(value: String): Fx[String] =
      if value == null then Fx.pure("NULL")
      else Fx.pure(StringHelper.enquoteNCharLiteral(value, backslashEscapesEnabled))

    override def isSimpleIdentifier(identifier: String): Fx[Boolean] =
      Fx.pure(StringHelper.isSimpleIdentifier(identifier))

    private def sqlMode: String = serverVariables.getOrElse("sql_mode", "")

    private def ansiQuotesEnabled: Boolean = sqlMode.contains("ANSI_QUOTES")

    private def backslashEscapesEnabled: Boolean = !sqlMode.contains("NO_BACKSLASH_ESCAPES")

    protected def checkClosed(): Fx[Unit] =
      isClosed().ifM(
        close() *> Fx.raiseError(new SQLException("No operations allowed after statement closed.")),
        Fx.unit
      )

    protected def checkNullOrEmptyQuery(sql: String): Fx[Unit] =
      if sql.isEmpty then Fx.raiseError(new SQLException("Can not issue empty query."))
      else if sql == null then Fx.raiseError(new SQLException("Can not issue NULL query."))
      else Fx.unit

    protected def useServerFetch(): Fx[Boolean] =
      fetchSize.get.map { fetchSize =>
        useCursorFetch && fetchSize > 0 && resultSetType == ResultSet.TYPE_FORWARD_ONLY
      }

    protected def buildBaseAttributes(protocol: Protocol): List[Attribute[?]] =
      List[Attribute[?]](
        DbAttributes.DbSystemName(DbAttributes.DbSystemNameValue.Mysql.value),
        ServerAttributes.ServerAddress(protocol.hostInfo.host),
        ServerAttributes.ServerPort(protocol.hostInfo.port.toLong),
        TelemetryAttribute.dbMysqlVersion(protocol.initialPacket.serverVersion.toString),
        TelemetryAttribute.dbMysqlThreadId(protocol.initialPacket.threadId)
      ) ++ protocol.hostInfo.database.map(name => DbAttributes.DbNamespace(name)).toList

    /**
     * Low-cardinality attributes suitable for metrics.
     * Excludes db.mysql.thread_id (per-connection) and db.query.text (per-query)
     * to avoid high-cardinality metric series.
     */
    protected def buildMetricsAttributes(protocol: Protocol): List[Attribute[?]] =
      List[Attribute[?]](
        DbAttributes.DbSystemName(DbAttributes.DbSystemNameValue.Mysql.value),
        ServerAttributes.ServerAddress(protocol.hostInfo.host),
        ServerAttributes.ServerPort(protocol.hostInfo.port.toLong)
      ) ++ protocol.hostInfo.database.map(name => DbAttributes.DbNamespace(name)).toList

    protected def withDurationMetrics[A](operation: Fx[A], metricsAttributes: Attribute[?]*): Fx[A] =
      Fx.monotonic.flatMap { startTime =>
        val record: Fx[Unit] =
          Fx.monotonic.flatMap(endTime =>
            databaseMetrics.recordOperationDuration(endTime - startTime, metricsAttributes*)
          )
        operation.flatTap(_ => record).handleErrorWith(error => record >> Fx.raiseError(error))
      }
