/**
 * Copyright (c) 2023-2026 by Takahiko Tominaga
 * This software is licensed under the MIT License (MIT).
 * For more information see LICENSE or https://opensource.org/licenses/MIT
 */

package ldbc.mysql.net.protocol

import java.util.concurrent.ConcurrentLinkedQueue

import scala.concurrent.duration.FiniteDuration
import scala.jdk.CollectionConverters.*

import ldbc.sql.{ Attribute, ResultSet }

import ldbc.effect.{ Concurrent, Ref }
import ldbc.fx.concurrentFx
import ldbc.fx.syntax.*
import ldbc.fx.Fx
import ldbc.fx.FxSuite
import ldbc.mysql.net.protocol.StatementImpl.ShareStatement
import ldbc.mysql.net.Protocol
import ldbc.telemetry.{ DatabaseMetrics, PoolMetricsState }

/**
 * Pins how [[StatementImpl.ShareStatement.withDurationMetrics]] behaves when the metrics backend itself
 * fails: the operation duration must be recorded exactly once, and a metrics failure must not turn a
 * successful statement into an error.
 *
 * `ldbc.pool.PoolTelemetryTest` pins the same property for the pool's connection-creation metric.
 */
class ShareStatementMetricsTest extends FxSuite:

  /**
   * A [[DatabaseMetrics]] that counts operation-duration recordings and optionally fails them.
   *
   * @param failRecording when true, every `recordOperationDuration` records the call and then raises
   */
  private final class RecordingMetrics(failRecording: Boolean) extends DatabaseMetrics[Fx]:
    private val calls: ConcurrentLinkedQueue[String] = new ConcurrentLinkedQueue[String]()

    def durationRecordings: Int = calls.iterator().asScala.count(_ == "operationDuration")

    override def recordOperationDuration(duration: FiniteDuration, attributes: Attribute[?]*): Fx[Unit] =
      Fx.delay { calls.add("operationDuration"); () } *>
        (if failRecording then Fx.raiseError(new RuntimeException("metrics backend is down")) else Fx.unit)

    override def recordReturnedRows(rows:             Long, attributes:     Attribute[?]*): Fx[Unit] = Fx.unit
    override def recordConnectionCreateTime(duration: FiniteDuration, poolName: String):    Fx[Unit] = Fx.unit
    override def recordConnectionWaitTime(duration:   FiniteDuration, poolName: String):    Fx[Unit] = Fx.unit
    override def recordConnectionUseTime(duration:    FiniteDuration, poolName: String):    Fx[Unit] = Fx.unit
    override def recordConnectionTimeout(poolName:    String):                              Fx[Unit] = Fx.unit
    override def registerPoolStateCallback(
      poolName:       String,
      minConnections: Int,
      maxConnections: Int,
      stateProvider:  Fx[PoolMetricsState]
    ): ldbc.effect.Resource[Fx, Unit] = ldbc.effect.Resource.pure(())

  /** The smallest [[ShareStatement]] that can drive `withDurationMetrics`. */
  private final class Harness(metrics: DatabaseMetrics[Fx]) extends ShareStatement[Fx]:
    override protected def F: Concurrent[Fx] = concurrentFx

    def record[A](operation: Fx[A]): Fx[A] = withDurationMetrics(operation)

    override val databaseMetrics:   DatabaseMetrics[Fx]            = metrics
    override val autoGeneratedKeys: Ref[Fx, Int]                   = Ref.unsafe[Fx, Int](0)
    override val connectionClosed:  Ref[Fx, Boolean]               = Ref.unsafe[Fx, Boolean](false)
    override val currentResultSet:  Ref[Fx, Option[ResultSet[Fx]]] = Ref.unsafe[Fx, Option[ResultSet[Fx]]](None)
    override val lastInsertId:      Ref[Fx, Long]                  = Ref.unsafe[Fx, Long](0L)
    override val moreResults:       Ref[Fx, Boolean]               = Ref.unsafe[Fx, Boolean](false)
    override val resultSetClosed:   Ref[Fx, Boolean]               = Ref.unsafe[Fx, Boolean](false)
    override val statementClosed:   Ref[Fx, Boolean]               = Ref.unsafe[Fx, Boolean](false)
    override val updateCount:       Ref[Fx, Long]                  = Ref.unsafe[Fx, Long](0L)
    override val fetchSize:         Ref[Fx, Int]                   = Ref.unsafe[Fx, Int](0)

    override def protocol:           Protocol[Fx]        = null.asInstanceOf[Protocol[Fx]]
    override def serverVariables:    Map[String, String] = Map.empty
    override def useCursorFetch:     Boolean             = false
    override def useServerPrepStmts: Boolean             = false
    override def resultSetType:      Int                 = ResultSet.TYPE_FORWARD_ONLY

    private def unsupported[A]: Fx[A] = Fx.raiseError(new UnsupportedOperationException("not needed for this test"))

    override def close():            Fx[Unit]              = Fx.unit
    override def clearBatch():       Fx[Unit]              = Fx.unit
    override def getGeneratedKeys(): Fx[ResultSet[Fx]]     = unsupported
    override def addBatch(sql:            String): Fx[Unit]              = unsupported
    override def execute(sql:             String): Fx[Boolean]           = unsupported
    override def executeQuery(sql:        String): Fx[ResultSet[Fx]]     = unsupported
    override def executeUpdate(sql:       String): Fx[Int]               = unsupported
    override def executeLargeUpdate(sql:  String): Fx[Long]              = unsupported
    override def executeLargeBatch():              Fx[Array[Long]]       = unsupported

  test("a successful operation records its duration exactly once") {
    val metrics = new RecordingMetrics(failRecording = false)
    new Harness(metrics).record(Fx.pure(42)).map { result =>
      assertEquals(result, 42)
      assertEquals(metrics.durationRecordings, 1)
    }
  }

  test("a failed operation records its duration exactly once and re-raises the original error") {
    val metrics = new RecordingMetrics(failRecording = false)
    val boom    = new RuntimeException("query failed")
    new Harness(metrics).record(Fx.raiseError[Int](boom)).attempt.map { result =>
      assertEquals(result, Left(boom))
      assertEquals(metrics.durationRecordings, 1)
    }
  }

  test("a failing metrics backend records the duration once, not twice") {
    val metrics = new RecordingMetrics(failRecording = true)
    new Harness(metrics).record(Fx.pure(42)).attempt.map { _ =>
      assertEquals(
        metrics.durationRecordings,
        1,
        "a failing recording must not be retried on the error path"
      )
    }
  }
