/**
 * Copyright (c) 2023-2026 by Takahiko Tominaga
 * This software is licensed under the MIT License (MIT).
 * For more information see LICENSE or https://opensource.org/licenses/MIT
 */

package ldbc.pool

import ldbc.fx.{ Fx, Ref }
import ldbc.fx.syntax.*

import ldbc.sql.*

/**
 * A configurable in-memory [[ldbc.sql.Connection]] over [[ldbc.fx.Fx]] for pool tests. It tracks the
 * calls the pool makes (validation, reset, close) so tests can assert on them, and lets validity be
 * toggled. Methods the pool never exercises raise `NotImplementedError`.
 *
 * @param validationCount incremented on every `isValid` / test-query execution
 * @param rollbackCount   incremented on every `rollback()`
 * @param autoCommitState the last value passed to `setAutoCommit`
 * @param closedRef       whether the connection has been closed
 * @param closeCount      incremented on every `close()`
 * @param isValidResult   the value `isValid` returns
 * @param executeResult   the value a statement's `execute` returns
 */
final class MockConnection(
  val validationCount: Ref[Int],
  val rollbackCount:   Ref[Int],
  val autoCommitState: Ref[Boolean],
  val closedRef:           Ref[Boolean],
  val closeCount:          Ref[Int],
  val statementCloseCount: Ref[Int],
  isValidResult:           Boolean,
  executeResult:           Boolean,
  isValidError:            Option[Throwable] = None
) extends Connection[Fx]:

  override def isValid(timeout: Int): Fx[Boolean] =
    validationCount.update(_ + 1) >> (isValidError match
      case Some(error) => Fx.raiseError(error)
      case None        => closedRef.get.map(closed => !closed && isValidResult))

  override def createStatement(): Fx[Statement[Fx]] =
    Fx.pure(new MockStatement(validationCount, statementCloseCount, executeResult))

  override def isClosed(): Fx[Boolean] = closedRef.get

  override def close(): Fx[Unit] = closeCount.update(_ + 1) >> closedRef.set(true)

  override def rollback(): Fx[Unit] = rollbackCount.update(_ + 1)

  override def getAutoCommit(): Fx[Boolean] = autoCommitState.get

  override def setAutoCommit(autoCommit: Boolean): Fx[Unit] = autoCommitState.set(autoCommit)

  override def commit(): Fx[Unit] = Fx.unit

  override def getTransactionIsolation(): Fx[Int] = Fx.pure(0)

  override def setTransactionIsolation(level: Int): Fx[Unit] = Fx.unit

  override def isReadOnly: Fx[Boolean] = Fx.pure(false)

  override def setReadOnly(readOnly: Boolean): Fx[Unit] = Fx.unit

  override def getCatalog(): Fx[String] = Fx.pure("")

  override def setCatalog(catalog: String): Fx[Unit] = Fx.unit

  override def getSchema(): Fx[String] = Fx.pure("")

  override def setSchema(schema: String): Fx[Unit] = Fx.unit

  override def createStatement(resultSetType: Int, resultSetConcurrency: Int): Fx[Statement[Fx]] =
    Fx.pure(new MockStatement(validationCount, statementCloseCount, executeResult))

  override def prepareStatement(sql: String): Fx[PreparedStatement[Fx]] = throw new NotImplementedError("prepareStatement")

  override def prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): Fx[PreparedStatement[Fx]] =
    throw new NotImplementedError("prepareStatement")

  override def prepareStatement(sql: String, autoGeneratedKeys: Int): Fx[PreparedStatement[Fx]] =
    throw new NotImplementedError("prepareStatement")

  override def prepareCall(sql: String): Fx[CallableStatement[Fx]] = throw new NotImplementedError("prepareCall")

  override def prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int): Fx[CallableStatement[Fx]] =
    throw new NotImplementedError("prepareCall")

  override def nativeSQL(sql: String): Fx[String] = Fx.pure(sql)

  override def getMetaData(): Fx[DatabaseMetaData[Fx]] = throw new NotImplementedError("getMetaData")

  override def setSavepoint(): Fx[Savepoint] = throw new NotImplementedError("setSavepoint")

  override def setSavepoint(name: String): Fx[Savepoint] = throw new NotImplementedError("setSavepoint")

  override def releaseSavepoint(savepoint: Savepoint): Fx[Unit] = Fx.unit

  override def rollback(savepoint: Savepoint): Fx[Unit] = rollbackCount.update(_ + 1)

/**
 * A minimal [[ldbc.sql.Statement]] used by [[MockConnection]] for test-query validation. Only
 * `execute`, `close`, and `isClosed` are exercised by the pool; everything else raises.
 *
 * @param validationCount     incremented on every `execute` so custom-test-query paths are observable
 * @param statementCloseCount incremented on every `close`, so statement-tracking can be asserted
 * @param executeResult       the value `execute` returns
 */
final class MockStatement(validationCount: Ref[Int], statementCloseCount: Ref[Int], executeResult: Boolean)
  extends Statement[Fx]:

  override def execute(sql: String): Fx[Boolean] = validationCount.update(_ + 1) >> Fx.pure(executeResult)

  override def close(): Fx[Unit] = statementCloseCount.update(_ + 1)

  override def isClosed(): Fx[Boolean] = Fx.pure(false)

  override def setFetchSize(rows: Int): Fx[Unit] = Fx.unit

  override def getFetchSize(): Fx[Int] = Fx.pure(0)

  override def addBatch(sql: String): Fx[Unit] = Fx.unit

  override def clearBatch(): Fx[Unit] = Fx.unit

  override def executeQuery(sql: String): Fx[ResultSet[Fx]] = throw new NotImplementedError("executeQuery")

  override def executeUpdate(sql: String): Fx[Int] = throw new NotImplementedError("executeUpdate")

  override def getResultSet(): Fx[Option[ResultSet[Fx]]] = Fx.pure(None)

  override def getUpdateCount(): Fx[Int] = Fx.pure(-1)

  override def getMoreResults(): Fx[Boolean] = Fx.pure(false)

  override def executeBatch(): Fx[Array[Int]] = throw new NotImplementedError("executeBatch")

  override def getGeneratedKeys(): Fx[ResultSet[Fx]] = throw new NotImplementedError("getGeneratedKeys")

  override def executeUpdate(sql: String, autoGeneratedKeys: Int): Fx[Int] = throw new NotImplementedError("executeUpdate")

  override def execute(sql: String, autoGeneratedKeys: Int): Fx[Boolean] = validationCount.update(_ + 1) >> Fx.pure(executeResult)

  override def getLargeUpdateCount(): Fx[Long] = throw new NotImplementedError("getLargeUpdateCount")

  override def executeLargeUpdate(sql: String): Fx[Long] = throw new NotImplementedError("executeLargeUpdate")

  override def executeLargeUpdate(sql: String, autoGeneratedKeys: Int): Fx[Long] =
    throw new NotImplementedError("executeLargeUpdate")

  override def executeLargeBatch(): Fx[Array[Long]] = throw new NotImplementedError("executeLargeBatch")

  override def enquoteLiteral(value: String): Fx[String] = throw new NotImplementedError("enquoteLiteral")

  override def enquoteIdentifier(identifier: String, alwaysQuote: Boolean): Fx[String] =
    throw new NotImplementedError("enquoteIdentifier")

  override def enquoteNCharLiteral(value: String): Fx[String] = throw new NotImplementedError("enquoteNCharLiteral")

  override def isSimpleIdentifier(identifier: String): Fx[Boolean] = throw new NotImplementedError("isSimpleIdentifier")

object MockConnection:

  /**
   * Creates a fresh [[MockConnection]] with its own tracking refs.
   *
   * @param isValidResult the value `isValid` returns (default `true`)
   * @param executeResult the value a statement's `execute` returns (default `true`)
   * @param isValidError  if set, `isValid` raises this instead of returning a value
   * @return an effect producing the mock connection
   */
  def apply(
    isValidResult: Boolean             = true,
    executeResult: Boolean             = true,
    isValidError:  Option[Throwable]   = None
  ): Fx[MockConnection] =
    for
      validationCount <- Ref.of(0)
      rollbackCount   <- Ref.of(0)
      autoCommitState <- Ref.of(true)
      closedRef           <- Ref.of(false)
      closeCount          <- Ref.of(0)
      statementCloseCount <- Ref.of(0)
    yield new MockConnection(
      validationCount,
      rollbackCount,
      autoCommitState,
      closedRef,
      closeCount,
      statementCloseCount,
      isValidResult,
      executeResult,
      isValidError
    )
