/**
 * Copyright (c) 2023-2025 by Takahiko Tominaga
 * This software is licensed under the MIT License (MIT).
 * For more information see LICENSE or https://opensource.org/licenses/MIT
 */

package ldbc.connector.pool

import java.nio.charset.Charset

import cats.effect.*
import cats.effect.std.Console

import munit.CatsEffectSuite

import ldbc.sql.*

import ldbc.connector.MySQLConfig

/**
 * Regression tests for bug #710:
 * PooledDataSource.validateConnection uses handleError, silently dropping the debug log effect.
 *
 * These tests call `validateConnection` directly on a real `PooledDataSource` instance
 * (created with `minConnections = 0` to avoid requiring a MySQL connection) and verify
 * whether the debug log is actually emitted when connection validation fails.
 *
 * - With the current buggy code (`handleError`): tests FAIL
 * - After applying the fix (`handleErrorWith`): tests PASS
 *
 * @see https://github.com/takapi327/ldbc/issues/710
 */
class ValidateConnectionLoggerTest extends CatsEffectSuite:

  /** A Console[IO] that records every println call to a Ref for later assertion. */
  private class RecordingConsole(ref: Ref[IO, List[String]]) extends Console[IO]:
    override def print[A](a:                  A)(implicit S: cats.Show[A]): IO[Unit]   = IO.unit
    override def println[A](a:                A)(implicit S: cats.Show[A]): IO[Unit]   = ref.update(_ :+ S.show(a))
    override def error[A](a:                  A)(implicit S: cats.Show[A]): IO[Unit]   = IO.unit
    override def errorln[A](a:                A)(implicit S: cats.Show[A]): IO[Unit]   = IO.unit
    override def readLine:                                                  IO[String] = IO.pure("")
    override def readLineWithCharset(charset: Charset):                     IO[String] = IO.pure("")

  /**
   * A mock Connection[IO] whose isClosed() returns false but isValid() raises the given error.
   * All other methods raise NotImplementedError since they are not called by validateConnection.
   */
  private def failingConnection(cause: Throwable): Connection[IO] =
    new Connection[IO]:
      private def stub[A]: IO[A] = IO.raiseError(new NotImplementedError("not used in validateConnection"))
      def createStatement():                                              IO[Statement[IO]]         = stub
      def prepareStatement(sql:          String):                         IO[PreparedStatement[IO]] = stub
      def prepareCall(sql:               String):                         IO[CallableStatement[IO]] = stub
      def nativeSQL(sql:                 String):                         IO[String]                = stub
      def setAutoCommit(autoCommit:      Boolean):                        IO[Unit]                  = stub
      def getAutoCommit():                                                IO[Boolean]               = stub
      def commit():                                                       IO[Unit]                  = stub
      def rollback():                                                     IO[Unit]                  = stub
      def close():                                                        IO[Unit]                  = IO.unit
      def isClosed():                                                     IO[Boolean]               = IO.pure(false)
      def getMetaData():                                                  IO[DatabaseMetaData[IO]]  = stub
      def setReadOnly(isReadOnly:        Boolean):                        IO[Unit]                  = stub
      def isReadOnly:                                                     IO[Boolean]               = stub
      def setCatalog(catalog:            String):                         IO[Unit]                  = stub
      def getCatalog():                                                   IO[String]                = stub
      def setTransactionIsolation(level: Int):                            IO[Unit]                  = stub
      def getTransactionIsolation():                                      IO[Int]                   = stub
      def createStatement(resultSetType: Int, resultSetConcurrency: Int): IO[Statement[IO]]         = stub
      def prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): IO[PreparedStatement[IO]] = stub
      def prepareCall(sql:      String, resultSetType: Int, resultSetConcurrency: Int): IO[CallableStatement[IO]] = stub
      def prepareStatement(sql:       String, autoGeneratedKeys: Int): IO[PreparedStatement[IO]] = stub
      def setSchema(schema:           String):                         IO[Unit]                  = stub
      def getSchema():                                                 IO[String]                = stub
      def isValid(timeout:            Int):                            IO[Boolean]               = IO.raiseError(cause)
      def setSavepoint():                                              IO[Savepoint]             = stub
      def setSavepoint(name:          String):                         IO[Savepoint]             = stub
      def rollback(savepoint:         Savepoint):                      IO[Unit]                  = stub
      def releaseSavepoint(savepoint: Savepoint):                      IO[Unit]                  = stub

  /**
   * MySQLConfig with minConnections=0 so that no actual MySQL connection is established
   * during pool initialization. debug=true enables poolLogger to emit [DEBUG] messages
   * via Console.println.
   *
   * The host/port/user values are irrelevant because no connection is ever created.
   */
  private val poolConfig = MySQLConfig.default
    .setMinConnections(0)
    .setMaxConnections(1)
    .setDebug(true) // enables: poolLogger.debug(msg) → Console.println(s"[DEBUG] $msg")

  // ---------------------------------------------------------------------------
  // isValid() path (connectionTestQuery = None, the default)
  // ---------------------------------------------------------------------------

  test("Bug #710: validateConnection silently drops debug log when isValid() fails") {
    Ref[IO].of(List.empty[String]).flatMap { logs =>
      given Console[IO] = RecordingConsole(logs)

      val conn = failingConnection(new RuntimeException("connection broken"))

      PooledDataSource.fromConfig[IO](poolConfig).use { ds =>
        for
          result   <- ds.validateConnection(conn)
          recorded <- logs.get
          debugLogs = recorded.filter(_.startsWith("[DEBUG]"))
        yield
          // validateConnection correctly returns false on failure
          assertEquals(result, false)
          // Bug #710: handleError { error => poolLogger.debug(...); false }
          // The F[Unit] from poolLogger.debug is created but immediately discarded.
          // The debug message is never written to Console.
          // → This assertion FAILS with the current (buggy) implementation.
          assert(
            debugLogs.exists(_.contains("validation failed")),
            s"Expected a [DEBUG] log about validation failure, but none was captured.\nCaptured output: $recorded"
          )
      }
    }
  }

  test("After fix: validateConnection correctly emits debug log when isValid() fails") {
    Ref[IO].of(List.empty[String]).flatMap { logs =>
      given Console[IO] = RecordingConsole(logs)

      val conn = failingConnection(new RuntimeException("connection broken"))

      PooledDataSource.fromConfig[IO](poolConfig).use { ds =>
        for
          result   <- ds.validateConnection(conn)
          recorded <- logs.get
          debugLogs = recorded.filter(_.startsWith("[DEBUG]"))
        yield
          assertEquals(result, false)
          // After the fix (handleError → handleErrorWith), the debug effect is properly
          // sequenced: poolLogger.debug(...).as(false)
          // → This assertion PASSES after applying the fix.
          assert(
            debugLogs.exists(_.contains("validation failed")),
            s"Expected a [DEBUG] log about validation failure, but none was captured.\nCaptured output: $recorded"
          )
      }
    }
  }
