/**
 * Copyright (c) 2023-2024 by Takahiko Tominaga
 * This software is licensed under the MIT License (MIT).
 * For more information see LICENSE or https://opensource.org/licenses/MIT
 */

package ldbc.sql

/**
 * The representation of a savepoint, which is a point within the current transaction that can be referenced from the Connection.rollback method.
 * When a transaction is rolled back to a savepoint all changes made after that savepoint are undone.
 * 
 * Savepoints can be either named or unnamed. Unnamed savepoints are identified by an ID generated by the underlying data source.
 */
trait Savepoint:

  /**
   * Retrieves the generated ID for the savepoint that this
   * <code>Savepoint</code> object represents.
   * @return the numeric ID of this savepoint
   */
  def getSavepointId(): Int

  /**
   * Retrieves the name of the savepoint that this Savepoint object represents.
   * 
   * @return
   *   the name of this savepoint
   */
  def getSavepointName(): String
