/**
 * Copyright (c) 2023-2025 by Takahiko Tominaga
 * This software is licensed under the MIT License (MIT).
 * For more information see LICENSE or https://opensource.org/licenses/MIT
 */

package ldbc.testkit

import cats.effect.IO
import cats.effect.kernel.Ref

import munit.CatsEffectSuite

import ldbc.sql.*

class TestConnectionTest extends CatsEffectSuite:

  /**
   * A minimal stub Connection[IO] whose `commit()`, `setAutoCommit()`, and `rollback()`
   * behaviors are configurable via callbacks. All other methods are not implemented and
   * will raise a [[NotImplementedError]] if called.
   */
  private def stub(
    onCommit:        IO[Unit] = IO.unit,
    onSetAutoCommit: Boolean => IO[Unit] = _ => IO.unit,
    onRollback:      IO[Unit] = IO.unit
  ): Connection[IO] = new Connection[IO]:
    private def notImpl[A]: IO[A] = IO.raiseError(new NotImplementedError("stub"))

    override def createStatement(): IO[Statement[IO]]                                                                  = notImpl
    override def prepareStatement(sql: String): IO[PreparedStatement[IO]]                                             = notImpl
    override def prepareCall(sql: String): IO[CallableStatement[IO]]                                                  = notImpl
    override def nativeSQL(sql: String): IO[String]                                                                   = notImpl
    override def setAutoCommit(autoCommit: Boolean): IO[Unit]                                                         = onSetAutoCommit(autoCommit)
    override def getAutoCommit(): IO[Boolean]                                                                         = IO.pure(false)
    override def commit(): IO[Unit]                                                                                    = onCommit
    override def rollback(): IO[Unit]                                                                                  = onRollback
    override def close(): IO[Unit]                                                                                     = IO.unit
    override def isClosed(): IO[Boolean]                                                                              = IO.pure(false)
    override def getMetaData(): IO[DatabaseMetaData[IO]]                                                              = notImpl
    override def setReadOnly(isReadOnly: Boolean): IO[Unit]                                                           = IO.unit
    override def isReadOnly: IO[Boolean]                                                                              = IO.pure(false)
    override def setCatalog(catalog: String): IO[Unit]                                                                = IO.unit
    override def getCatalog(): IO[String]                                                                             = IO.pure("")
    override def setTransactionIsolation(level: Int): IO[Unit]                                                        = IO.unit
    override def getTransactionIsolation(): IO[Int]                                                                   = IO.pure(Connection.TRANSACTION_REPEATABLE_READ)
    override def createStatement(resultSetType: Int, resultSetConcurrency: Int): IO[Statement[IO]]                    = notImpl
    override def prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): IO[PreparedStatement[IO]] = notImpl
    override def prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int): IO[CallableStatement[IO]]   = notImpl
    override def prepareStatement(sql: String, autoGeneratedKeys: Int): IO[PreparedStatement[IO]]                     = notImpl
    override def setSchema(schema: String): IO[Unit]                                                                  = IO.unit
    override def getSchema(): IO[String]                                                                              = IO.pure("")
    override def isValid(timeout: Int): IO[Boolean]                                                                   = IO.pure(true)
    override def setSavepoint(): IO[Savepoint]                                                                        = notImpl
    override def setSavepoint(name: String): IO[Savepoint]                                                           = notImpl
    override def rollback(savepoint: Savepoint): IO[Unit]                                                             = IO.unit
    override def releaseSavepoint(savepoint: Savepoint): IO[Unit]                                                     = IO.unit

  test("commit() is intercepted as a no-op and does not delegate to the underlying connection") {
    for
      commitCalled <- Ref.of[IO, Boolean](false)
      conn = new TestConnection[IO](stub(onCommit = commitCalled.set(true)))
      _ <- conn.commit()
      called <- commitCalled.get
    yield assertEquals(called, false)
  }

  test("setAutoCommit() is intercepted as a no-op regardless of the argument value") {
    for
      autoCommitCalled <- Ref.of[IO, Boolean](false)
      conn = new TestConnection[IO](stub(onSetAutoCommit = _ => autoCommitCalled.set(true)))
      _ <- conn.setAutoCommit(true)
      _ <- conn.setAutoCommit(false)
      called <- autoCommitCalled.get
    yield assertEquals(called, false)
  }

  test("rollback() delegates to the underlying connection") {
    for
      rollbackCalled <- Ref.of[IO, Boolean](false)
      conn = new TestConnection[IO](stub(onRollback = rollbackCalled.set(true)))
      _ <- conn.rollback()
      called <- rollbackCalled.get
    yield assert(called)
  }
