/**
 * Copyright (c) 2023-2025 by Takahiko Tominaga
 * This software is licensed under the MIT License (MIT).
 * For more information see LICENSE or https://opensource.org/licenses/MIT
 */

package jdbc.connector

import cats.syntax.all.*

import cats.effect.Sync

import ldbc.sql.{ ResultSet, Statement }

private[jdbc] case class StatementImpl[F[_]: Sync](statement: java.sql.Statement) extends Statement[F]:

  override def executeQuery(sql: String): F[ResultSet[F]] =
    Sync[F].blocking(statement.executeQuery(sql)).map(ResultSetImpl.apply)

  override def executeUpdate(sql: String): F[Int] = Sync[F].blocking(statement.executeUpdate(sql))

  override def close(): F[Unit] = Sync[F].blocking(statement.close())

  override def execute(sql: String): F[Boolean] = Sync[F].blocking(statement.execute(sql))

  override def getResultSet(): F[Option[ResultSet[F]]] =
    Sync[F].blocking(Option(statement.getResultSet)).map(_.map(ResultSetImpl.apply))

  override def getUpdateCount(): F[Int] = Sync[F].blocking(statement.getUpdateCount)

  override def getMoreResults(): F[Boolean] = Sync[F].blocking(statement.getMoreResults)

  override def setFetchSize(rows: Int): F[Unit] = Sync[F].pure(statement.setFetchSize(rows))

  override def getFetchSize(): F[Int] = Sync[F].pure(statement.getFetchSize)

  override def addBatch(sql: String): F[Unit] = Sync[F].blocking(statement.addBatch(sql))

  override def clearBatch(): F[Unit] = Sync[F].blocking(statement.clearBatch())

  override def executeBatch(): F[Array[Int]] = Sync[F].blocking(statement.executeBatch())

  override def getGeneratedKeys(): F[ResultSet[F]] =
    Sync[F].blocking(statement.getGeneratedKeys).map(ResultSetImpl.apply)

  override def executeUpdate(sql: String, autoGeneratedKeys: Int): F[Int] =
    Sync[F].blocking(statement.executeUpdate(sql, autoGeneratedKeys))

  override def execute(sql: String, autoGeneratedKeys: Int): F[Boolean] =
    Sync[F].blocking(statement.execute(sql, autoGeneratedKeys))

  override def isClosed(): F[Boolean] = Sync[F].blocking(statement.isClosed)

  override def getLargeUpdateCount(): F[Long] = Sync[F].blocking(statement.getLargeUpdateCount)

  override def executeLargeUpdate(sql: String): F[Long] =
    Sync[F].blocking(statement.executeLargeUpdate(sql))

  override def executeLargeUpdate(sql: String, autoGeneratedKeys: Int): F[Long] =
    Sync[F].blocking(statement.executeLargeUpdate(sql, autoGeneratedKeys))

  override def executeLargeBatch(): F[Array[Long]] =
    Sync[F].blocking(statement.executeLargeBatch())

  override def enquoteLiteral(value: String): F[String] =
    Sync[F].blocking(Enquoting.enquoteLiteral(statement, value))

  override def enquoteIdentifier(identifier: String, alwaysQuote: Boolean): F[String] =
    Sync[F].blocking(Enquoting.enquoteIdentifier(statement, identifier, alwaysQuote))

  override def enquoteNCharLiteral(value: String): F[String] =
    Sync[F].blocking(Enquoting.enquoteNCharLiteral(statement, value))

  override def isSimpleIdentifier(identifier: String): F[Boolean] =
    Sync[F].blocking(Enquoting.isSimpleIdentifier(statement, identifier))

/**
 * `java.sql.Statement` gained the enquote methods in Java 9 (JDBC 4.3), while this module is
 * compiled against the Java 8 API, so they must be invoked reflectively through the
 * `java.sql.Statement` interface.
 */
private[connector] object Enquoting:

  private def method(name: String, parameterTypes: Class[?]*): java.lang.reflect.Method =
    classOf[java.sql.Statement].getMethod(name, parameterTypes*)

  private lazy val enquoteLiteralMethod      = method("enquoteLiteral", classOf[String])
  private lazy val enquoteIdentifierMethod   = method("enquoteIdentifier", classOf[String], java.lang.Boolean.TYPE)
  private lazy val enquoteNCharLiteralMethod = method("enquoteNCharLiteral", classOf[String])
  private lazy val isSimpleIdentifierMethod  = method("isSimpleIdentifier", classOf[String])

  private def invoke[A](statement: java.sql.Statement, method: java.lang.reflect.Method, args: AnyRef*): A =
    try method.invoke(statement, args*).asInstanceOf[A]
    catch case e: java.lang.reflect.InvocationTargetException => throw e.getCause

  def enquoteLiteral(statement: java.sql.Statement, value: String): String =
    invoke[String](statement, enquoteLiteralMethod, value)

  def enquoteIdentifier(statement: java.sql.Statement, identifier: String, alwaysQuote: Boolean): String =
    invoke[String](statement, enquoteIdentifierMethod, identifier, java.lang.Boolean.valueOf(alwaysQuote))

  def enquoteNCharLiteral(statement: java.sql.Statement, value: String): String =
    invoke[String](statement, enquoteNCharLiteralMethod, value)

  def isSimpleIdentifier(statement: java.sql.Statement, identifier: String): Boolean =
    invoke[java.lang.Boolean](statement, isSimpleIdentifierMethod, identifier).booleanValue()
