/** This file is part of the ldbc. For the full copyright and license information, please view the LICENSE file that was
 * distributed with this source code.
 */

package ldbc.dsl.syntax

import org.scalatest.flatspec.AnyFlatSpec

class QuerySyntaxTest extends AnyFlatSpec:

  it should "It can be converted to the model specified by the toList method." in {
    assertCompiles(
      """
        |import cats.effect.IO
        |
        |import ldbc.core.*
        |import ldbc.dsl.io.{ *, given }
        |import ldbc.dsl.logging.LogHandler
        |import ldbc.query.builder.TableQuery
        |
        |case class User(id: Long, name: String, age: Int)
        |object User:
        |  val table = Table[User]("user")(
        |    column("id", BIGINT, AUTO_INCREMENT, PRIMARY_KEY),
        |    column("name", VARCHAR(255)),
        |    column("age", INT)
        |  )
        |
        |val user = TableQuery[IO, User](User.table)
        |
        |given LogHandler[IO] = LogHandler.consoleLogger
        |val query = user.selectAll.toList[User]
        |""".stripMargin
    )
  }

  it should "If the Tuple generated by the toList method does not match the type of the specified model property, a Compile error occurs." in {
    assertDoesNotCompile(
      """
        |import cats.effect.IO
        |
        |import ldbc.core.*
        |import ldbc.dsl.io.{ *, given }
        |import ldbc.dsl.logging.LogHandler
        |import ldbc.query.builder.TableQuery
        |
        |case class User(id: Long, name: String, age: Int)
        |object User:
        |  val table = Table[User]("user")(
        |    column("id", BIGINT, AUTO_INCREMENT, PRIMARY_KEY),
        |    column("name", VARCHAR(255)),
        |    column("age", INT)
        |  )
        |
        |val user = TableQuery[IO, User](User.table)
        |
        |given LogHandler[IO] = LogHandler.consoleLogger
        |case class FailedUser(id: Long, name: String, age: Option[Int])
        |val query = user.selectAll.toList[FailedUser]
        |""".stripMargin
    )
  }

  it should "The type of Tuple generated by the toList method matches the specified type." in {
    assertCompiles(
      """
        |import cats.data.Kleisli
        |import cats.effect.IO
        |
        |import ldbc.core.*
        |import ldbc.sql.Connection
        |import ldbc.dsl.io.{ *, given }
        |import ldbc.dsl.logging.LogHandler
        |import ldbc.query.builder.TableQuery
        |
        |case class User(id: Long, name: String, age: Int)
        |object User:
        |  val table = Table[User]("user")(
        |    column("id", BIGINT, AUTO_INCREMENT, PRIMARY_KEY),
        |    column("name", VARCHAR(255)),
        |    column("age", INT)
        |  )
        |
        |val user = TableQuery[IO, User](User.table)
        |
        |given LogHandler[IO] = LogHandler.consoleLogger
        |val query: Kleisli[IO, Connection[IO], List[(Long, String, Int)]] = user.selectAll.toList
        |""".stripMargin
    )
  }

  it should "It can be converted to the model specified by the headOption method." in {
    assertCompiles(
      """
        |import cats.effect.IO
        |
        |import ldbc.core.*
        |import ldbc.dsl.io.{ *, given }
        |import ldbc.dsl.logging.LogHandler
        |import ldbc.query.builder.TableQuery
        |
        |case class User(id: Long, name: String, age: Int)
        |object User:
        |  val table = Table[User]("user")(
        |    column("id", BIGINT, AUTO_INCREMENT, PRIMARY_KEY),
        |    column("name", VARCHAR(255)),
        |    column("age", INT)
        |  )
        |
        |val user = TableQuery[IO, User](User.table)
        |
        |given LogHandler[IO] = LogHandler.consoleLogger
        |val query = user.selectAll.where(_.id === 1).headOption[User]
        |""".stripMargin
    )
  }

  it should "If the Tuple generated by the headOption method does not match the type of the specified model property, a Compile error occurs." in {
    assertDoesNotCompile(
      """
        |import cats.effect.IO
        |
        |import ldbc.core.*
        |import ldbc.dsl.io.{ *, given }
        |import ldbc.dsl.logging.LogHandler
        |import ldbc.query.builder.TableQuery
        |
        |case class User(id: Long, name: String, age: Int)
        |object User:
        |  val table = Table[User]("user")(
        |    column("id", BIGINT, AUTO_INCREMENT, PRIMARY_KEY),
        |    column("name", VARCHAR(255)),
        |    column("age", INT)
        |  )
        |
        |val user = TableQuery[IO, User](User.table)
        |
        |given LogHandler[IO] = LogHandler.consoleLogger
        |case class FailedUser(id: Long, name: String, age: Option[Int])
        |val query = user.selectAll.where(_.id === 1).headOption[FailedUser]
        |""".stripMargin
    )
  }

  it should "The type of Tuple generated by the headOption method matches the specified type." in {
    assertCompiles(
      """
        |import cats.data.Kleisli
        |import cats.effect.IO
        |
        |import ldbc.core.*
        |import ldbc.sql.Connection
        |import ldbc.dsl.io.{ *, given }
        |import ldbc.dsl.logging.LogHandler
        |import ldbc.query.builder.TableQuery
        |
        |case class User(id: Long, name: String, age: Int)
        |object User:
        |  val table = Table[User]("user")(
        |    column("id", BIGINT, AUTO_INCREMENT, PRIMARY_KEY),
        |    column("name", VARCHAR(255)),
        |    column("age", INT)
        |  )
        |
        |val user = TableQuery[IO, User](User.table)
        |
        |given LogHandler[IO] = LogHandler.consoleLogger
        |val query: Kleisli[IO, Connection[IO], Option[(Long, String, Int)]] = user.selectAll.where(_.id === 1).headOption
        |""".stripMargin
    )
  }

  it should "It can be converted to the model specified by the unsafe method." in {
    assertCompiles(
      """
        |import cats.data.Kleisli
        |import cats.effect.IO
        |
        |import ldbc.core.*
        |import ldbc.sql.Connection
        |import ldbc.dsl.io.{ *, given }
        |import ldbc.dsl.logging.LogHandler
        |import ldbc.query.builder.TableQuery
        |
        |case class User(id: Long, name: String, age: Int)
        |object User:
        |  val table = Table[User]("user")(
        |    column("id", BIGINT, AUTO_INCREMENT, PRIMARY_KEY),
        |    column("name", VARCHAR(255)),
        |    column("age", INT)
        |  )
        |
        |val user = TableQuery[IO, User](User.table)
        |
        |given LogHandler[IO] = LogHandler.consoleLogger
        |val query: Kleisli[IO, Connection[IO], User] = user.selectAll.where(_.id === 1).unsafe[User]
        |""".stripMargin
    )
  }

  it should "If the Tuple generated by the unsafe method does not match the type of the specified model property, a Compile error occurs." in {
    assertDoesNotCompile(
      """
        |import cats.effect.IO
        |
        |import ldbc.core.*
        |import ldbc.dsl.io.{ *, given }
        |import ldbc.dsl.logging.LogHandler
        |import ldbc.query.builder.TableQuery
        |
        |case class User(id: Long, name: String, age: Int)
        |object User:
        |  val table = Table[User]("user")(
        |    column("id", BIGINT, AUTO_INCREMENT, PRIMARY_KEY),
        |    column("name", VARCHAR(255)),
        |    column("age", INT)
        |  )
        |
        |val user = TableQuery[IO, User](User.table)
        |
        |given LogHandler[IO] = LogHandler.consoleLogger
        |case class FailedUser(id: Long, name: String, age: Option[Int])
        |val query = user.selectAll.where(_.id === 1).unsafe[FailedUser]
        |""".stripMargin
    )
  }

  it should "The type of Tuple generated by the unsafe method matches the specified type." in {
    assertCompiles(
      """
        |import cats.data.Kleisli
        |import cats.effect.IO
        |
        |import ldbc.core.*
        |import ldbc.sql.Connection
        |import ldbc.dsl.io.{ *, given }
        |import ldbc.dsl.logging.LogHandler
        |import ldbc.query.builder.TableQuery
        |
        |case class User(id: Long, name: String, age: Int)
        |object User:
        |  val table = Table[User]("user")(
        |    column("id", BIGINT, AUTO_INCREMENT, PRIMARY_KEY),
        |    column("name", VARCHAR(255)),
        |    column("age", INT)
        |  )
        |
        |val user = TableQuery[IO, User](User.table)
        |
        |given LogHandler[IO] = LogHandler.consoleLogger
        |val query: Kleisli[IO, Connection[IO], (Long, String, Int)] = user.selectAll.where(_.id === 1).unsafe
        |""".stripMargin
    )
  }
