/**
 * Copyright (c) 2023-2026 by Takahiko Tominaga
 * This software is licensed under the MIT License (MIT).
 * For more information see LICENSE or https://opensource.org/licenses/MIT
 */

package ldbc.future

import scala.concurrent.ExecutionContext.Implicits.global

import munit.FunSuite

import ldbc.fx.Fx

import ldbc.sql.*

import ldbc.dsl.*

class ConnectorTest extends FunSuite:

  private def notImpl[A]: Fx[A] = Fx.raiseError(new NotImplementedError("stub"))

  /** A Connection whose every operation is unimplemented; used where no operation is actually invoked. */
  private class StubConnection extends Connection[Fx]:
    override def createStatement():                       Fx[Statement[Fx]]         = notImpl
    override def prepareStatement(sql: String):           Fx[PreparedStatement[Fx]] = notImpl
    override def prepareCall(sql:      String):           Fx[CallableStatement[Fx]] = notImpl
    override def nativeSQL(sql:        String):           Fx[String]                = notImpl
    override def setAutoCommit(autoCommit: Boolean):      Fx[Unit]                  = notImpl
    override def getAutoCommit():                         Fx[Boolean]               = notImpl
    override def commit():                                Fx[Unit]                  = notImpl
    override def rollback():                              Fx[Unit]                  = notImpl
    override def close():                                 Fx[Unit]                  = notImpl
    override def isClosed():                              Fx[Boolean]               = notImpl
    override def getMetaData():                           Fx[DatabaseMetaData[Fx]]  = notImpl
    override def setReadOnly(isReadOnly: Boolean):        Fx[Unit]                  = notImpl
    override def isReadOnly:                              Fx[Boolean]               = notImpl
    override def setCatalog(catalog: String):             Fx[Unit]                  = notImpl
    override def getCatalog():                            Fx[String]                = notImpl
    override def setTransactionIsolation(level: Int):     Fx[Unit]                  = notImpl
    override def getTransactionIsolation():               Fx[Int]                   = notImpl
    override def createStatement(resultSetType: Int, resultSetConcurrency: Int): Fx[Statement[Fx]] = notImpl
    override def prepareStatement(
      sql:                  String,
      resultSetType:        Int,
      resultSetConcurrency: Int
    ): Fx[PreparedStatement[Fx]] = notImpl
    override def prepareStatement(sql: String, autoGeneratedKeys: Int): Fx[PreparedStatement[Fx]] = notImpl
    override def prepareCall(
      sql:                  String,
      resultSetType:        Int,
      resultSetConcurrency: Int
    ): Fx[CallableStatement[Fx]] = notImpl
    override def setSchema(schema: String):        Fx[Unit]      = notImpl
    override def getSchema():                      Fx[String]    = notImpl
    override def isValid(timeout: Int):            Fx[Boolean]   = notImpl
    override def setSavepoint():                   Fx[Savepoint] = notImpl
    override def setSavepoint(name: String):       Fx[Savepoint] = notImpl
    override def rollback(savepoint: Savepoint):   Fx[Unit]      = notImpl
    override def releaseSavepoint(savepoint: Savepoint): Fx[Unit] = notImpl

  private val stubDataSource: DataSource[Fx] = new DataSource[Fx]:
    override def getConnection: Fx[(Connection[Fx], Fx[Unit])] = Fx.pure((new StubConnection, Fx.unit))

  test("toFuture delivers a pure value") {
    toFuture(Fx.pure(42)).map(assertEquals(_, 42))
  }

  test("toFuture surfaces errors as a failed Future") {
    toFuture(Fx.raiseError[Int](new RuntimeException("boom"))).failed.map(e => assertEquals(e.getMessage, "boom"))
  }

  test("Connector.fromDataSource runs a DBIO and returns its value") {
    Connector.fromDataSource(stubDataSource).run(DBIO.pure(42)).map(assertEquals(_, 42))
  }

  test("Connector.fromConnection runs a DBIO against the given connection") {
    Connector.fromConnection(new StubConnection).run(DBIO.pure(7)).map(assertEquals(_, 7))
  }

  test("Connector propagates DBIO errors as a failed Future") {
    Connector
      .fromConnection(new StubConnection)
      .run(DBIO.raiseError[Int](new RuntimeException("dbio-boom")))
      .failed
      .map(e => assertEquals(e.getMessage, "dbio-boom"))
  }
