/**
 * Copyright (c) 2023-2026 by Takahiko Tominaga
 * This software is licensed under the MIT License (MIT).
 * For more information see LICENSE or https://opensource.org/licenses/MIT
 */

package ldbc.telemetry

/**
 * The instrument kind a [[DbMetric]] is recorded on. Backends map these onto whatever their metrics
 * library calls the same concept.
 */
enum InstrumentKind:
  /** A distribution of values with explicit bucket boundaries. */
  case Histogram

  /** A monotonically increasing count. */
  case Counter

  /** A non-monotonic value read from a callback at export time. */
  case ObservableUpDownCounter

/**
 * The bucket boundaries fixed by the OpenTelemetry database metrics semantic conventions. Kept private so
 * the boundaries are only ever reached through the metric that uses them.
 */
private object Boundaries:

  /** `[0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10]` seconds. */
  val duration: List[Double] = List(0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0)

  /** `[1, 2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000]` rows. */
  val returnedRows: List[Double] =
    List(1.0, 2.0, 5.0, 10.0, 20.0, 50.0, 100.0, 200.0, 500.0, 1000.0, 2000.0, 5000.0, 10000.0)

/**
 * The metric instruments the driver and the pool emit, inlined from the OpenTelemetry database metrics
 * semantic conventions (v1.39.0).
 *
 * They live here, in the CE-free core, so that every backend (`ldbc-otel4s`, `ldbc-zio-telemetry`, ...)
 * creates the *same* instruments from a single definition. Backends differ in how they build an
 * instrument, not in what it is called, what unit it carries, or how its buckets are laid out — which is
 * what would silently drift if each spelled the descriptors out itself. This mirrors how
 * [[ldbc.telemetry.DbAttributes]] inlines the attribute keys rather than depending on a semconv artifact.
 *
 * Being an `enum` rather than a set of values plus a hand-written list means [[DbMetric.values]] is
 * generated by the compiler: a metric cannot be declared and then forgotten when the backends' tests
 * iterate over every metric.
 *
 * @param name        the instrument name, e.g. `db.client.operation.duration`
 * @param unit        the UCUM unit or the curly-brace annotation, e.g. `s` or `{connection}`
 * @param description the human-readable description exported alongside the metric
 * @param kind        the instrument kind
 * @param boundaries  explicit bucket boundaries, for [[InstrumentKind.Histogram]] only
 *
 * @see [[https://opentelemetry.io/docs/specs/semconv/database/database-metrics/]]
 */
enum DbMetric(
  val name:        String,
  val unit:        String,
  val description: String,
  val kind:        InstrumentKind,
  val boundaries:  List[Double] = Nil
):

  /** `db.client.operation.duration` — how long a database client operation took. */
  case ClientOperationDuration
    extends DbMetric(
      "db.client.operation.duration",
      "s",
      "Duration of database client operations.",
      InstrumentKind.Histogram,
      Boundaries.duration
    )

  /** `db.client.response.returned_rows` — how many rows an operation returned. */
  case ClientResponseReturnedRows
    extends DbMetric(
      "db.client.response.returned_rows",
      "{row}",
      "The actual number of records returned by the database operation.",
      InstrumentKind.Histogram,
      Boundaries.returnedRows
    )

  /** `db.client.connection.create_time` — how long establishing a new physical connection took. */
  case ClientConnectionCreateTime
    extends DbMetric(
      "db.client.connection.create_time",
      "s",
      "The time it took to create a new connection.",
      InstrumentKind.Histogram,
      Boundaries.duration
    )

  /** `db.client.connection.wait_time` — how long acquiring a connection from the pool took. */
  case ClientConnectionWaitTime
    extends DbMetric(
      "db.client.connection.wait_time",
      "s",
      "The time it took to obtain an open connection from the pool.",
      InstrumentKind.Histogram,
      Boundaries.duration
    )

  /** `db.client.connection.use_time` — how long a borrowed connection was held. */
  case ClientConnectionUseTime
    extends DbMetric(
      "db.client.connection.use_time",
      "s",
      "The time between borrowing a connection and returning it to the pool.",
      InstrumentKind.Histogram,
      Boundaries.duration
    )

  /** `db.client.connection.timeouts` — how many acquisitions timed out. */
  case ClientConnectionTimeouts
    extends DbMetric(
      "db.client.connection.timeouts",
      "{timeout}",
      "The number of connection timeouts that have occurred trying to obtain a connection from the pool.",
      InstrumentKind.Counter
    )

  /** `db.client.connection.count` — connections per [[DbAttributes.DbClientConnectionState]]. */
  case ClientConnectionCount
    extends DbMetric(
      "db.client.connection.count",
      "{connection}",
      "The number of connections that are currently in state described by the `state` attribute.",
      InstrumentKind.ObservableUpDownCounter
    )

  /** `db.client.connection.idle.max` — the configured upper bound on idle connections. */
  case ClientConnectionIdleMax
    extends DbMetric(
      "db.client.connection.idle.max",
      "{connection}",
      "The maximum number of idle open connections allowed.",
      InstrumentKind.ObservableUpDownCounter
    )

  /** `db.client.connection.idle.min` — the configured lower bound on idle connections. */
  case ClientConnectionIdleMin
    extends DbMetric(
      "db.client.connection.idle.min",
      "{connection}",
      "The minimum number of idle open connections allowed.",
      InstrumentKind.ObservableUpDownCounter
    )

  /** `db.client.connection.max` — the configured maximum pool size. */
  case ClientConnectionMax
    extends DbMetric(
      "db.client.connection.max",
      "{connection}",
      "The maximum number of open connections allowed.",
      InstrumentKind.ObservableUpDownCounter
    )

  /** `db.client.connection.pending_requests` — how many callers are waiting for a connection. */
  case ClientConnectionPendingRequests
    extends DbMetric(
      "db.client.connection.pending_requests",
      "{request}",
      "The number of current pending requests for an open connection.",
      InstrumentKind.ObservableUpDownCounter
    )

object DbMetric:

  /**
   * The metrics registered through [[DatabaseMetrics.registerPoolStateCallback]] — every observable
   * instrument, derived rather than listed so it cannot fall out of step with the cases above.
   */
  val poolStateGauges: List[DbMetric] =
    values.filter(_.kind == InstrumentKind.ObservableUpDownCounter).toList
